export const adminLabels = {
  moduleTitle: "Admin",
  systemTitle: "System",
  smtpOperationsTitle: "SMTP Operations",
  navMailOperations: "Merkezi Mail Operasyonları",
  mailOperationsTitle: "Merkezi Mail Operasyonları",
  mailOperationsSubtitle: "Tüm mail gönderim operasyonlarını merkezi olarak görüntüleyin",
  mailOperationsExport: "Export",
  mailOperationsExportSoon: "Export özelliği yakında eklenecek",
  mailOperationsEmptyTitle: "Henüz mail operasyonu kaydı yok",
  mailOperationsEmptyDescription:
    "Henüz kayıt yok. SMTP test veya diğer mail gönderimleri tamamlandıkça operasyonlar burada listelenir.",
  mailOperationsLoadError: "Mail operasyonları yüklenemedi.",
  mailOperationsFilterSearch: "Ara",
  mailOperationsFilterSearchPlaceholder: "Müşteri, alıcı e-posta veya konu...",
  mailOperationsFilterStatus: "Durum",
  mailOperationsFilterSource: "Kaynak / Tip",
  mailOperationsFilterSmtp: "SMTP Hesabı",
  mailOperationsFilterFair: "Fuar",
  mailOperationsFilterDateFrom: "Başlangıç",
  mailOperationsFilterDateTo: "Bitiş",
  mailOperationsFilterAll: "Tümü",
  mailOperationsColDate: "Tarih",
  mailOperationsColSource: "Kaynak / Tip",
  mailOperationsColFair: "Fuar",
  mailOperationsColCustomer: "Müşteri",
  mailOperationsColRecipientEmail: "Alıcı Email",
  mailOperationsColSmtpAccount: "SMTP Hesabı",
  mailOperationsColTemplate: "Şablon",
  mailOperationsColSubject: "Konu",
  mailOperationsColStatus: "Status",
  mailOperationsColError: "Hata Mesajı",
  mailOperationsColActions: "İşlem",
  mailOperationsDemoBanner:
    "Örnek veriler gösteriliyor. Merkezi mail operasyonları API entegrasyonu sonraki aşamada eklenecek.",
  mailOperationsActionsMenuLabel: "İşlemler",
  mailOperationsDetailTitle: "Mail Operasyon Detayı",
  mailOperationsLogsTitle: "Teknik Süreç Logları",
  mailOperationsErrorTitle: "Hata Detayı",
  mailOperationsRetryTitle: "Maili Yeniden Dene",
  mailOperationsRetryMessage:
    "Bu başarısız mail tekrar gönderilecek. Devam edilsin mi?",
  mailOperationsRetrySuccess: "Mail yeniden gönderildi.",
  mailOperationsRetryFailed: "Mail yeniden gönderilemedi.",
  mailOperationsRetryInProgress: "Yeniden gönderiliyor…",
  mailOperationsCancelTitle: "Maili İptal Et",
  mailOperationsCancelMessage:
    "Kuyruktaki bu mail operasyonu iptal edilsin mi? (Backend entegrasyonu yakında)",
  mailOperationsRetryTodo: "Retry işlemi henüz bağlanmadı (TODO).",
  mailOperationsCancelTodo: "İptal işlemi henüz bağlanmadı (TODO).",
  mailOperationsCopySuccess: "Mail operasyon özeti panoya kopyalandı.",
  mailOperationsCopyError: "Panoya kopyalanamadı.",
  mailOperationsNoLogs: "Log kaydı bulunmuyor.",
  mailOperationsNoError: "Hata mesajı yok.",
  mailOperationsStatusLabels: {
    queued: "Kuyrukta",
    sending: "Gönderiliyor",
    sent: "Gönderildi",
    failed: "Başarısız",
    cancelled: "İptal Edildi",
    skipped: "Atlandı",
  },
  mailOperationsSourceLabels: {
    smtp_test: "SMTP Test",
    template_test: "Şablon Test",
    fair_bulk_email: "Fuar Toplu Mail",
    system_notification: "Sistem Bildirimi",
    manual_email: "Manuel E-posta",
  },
  mailOperationsActionLabels: {
    detail: "Detay",
    logs: "Logları Gör",
    copy: "Kopyala",
    retry: "Tekrar Gönder",
    error_detail: "Hata Detayı",
    cancel: "İptal Et",
  },
  systemSubtitle: "Sistem yönetimi ve operasyon araçları",
  navDatabaseBackups: "Database Backups",
  navSmtpAccounts: "SMTP Hesapları",
  comingSoon: "Yakında",
  comingSoonMessage: "Bu özellik yakında kullanıma sunulacak.",

  backupsTitle: "Database Backups",
  backupsSubtitle: "Disaster recovery, SQL export ve taşınabilir veri paketleri",
  newBackup: "+ New Backup",
  newBackupTitle: "Yeni Veritabanı Yedeği",
  formatLabel: "Format",
  formatPostgresqlDump: "PostgreSQL Native Backup (.dump)",
  formatPostgresqlDumpDesc:
    "Tam geri yükleme için önerilir. En güvenli restore formatıdır.",
  formatPostgresqlSql: "PostgreSQL SQL Script (.sql)",
  formatPostgresqlSqlDesc:
    "PostgreSQL uyumlu düz SQL çıktısıdır. Navicat, DBeaver, DataGrip gibi araçlarda inceleme/import için uygundur.",
  formatUniversalPackage: "Universal Data Package (.zip)",
  formatUniversalPackageDesc:
    "Platform bağımsız JSON + manifest veri paketi. Gelecekte MSSQL, MySQL veya başka CRM sistemlerine migration için kullanılacaktır.",
  formatPostgresqlDumpShort: "DR (.dump)",
  formatPostgresqlSqlShort: "SQL (.sql)",
  formatUniversalPackageShort: "Data Package (.zip)",
  notesLabel: "Açıklama",
  notesPlaceholder: "Örn: Maktek import testi öncesi",
  notesHint: "İsteğe bağlı. Bu yedek neden alındığını not edin.",
  startBackup: "Yedeği Başlat",
  cancel: "İptal",

  databaseKeysLabel: "Yedeklenecek veritabanları",
  databaseKeyKyroxCore: "KYROX Core",
  databaseKeyFairCrm: "FAIR CRM",
  databaseKeyKyroxCoreDesc: "Kullanıcılar, organizasyonlar, roller, yetkiler ve oturum tabloları",
  databaseKeyFairCrmDesc: "Müşteriler, fuarlar, contacts, görevler, SMTP ve CRM verileri",
  databaseKeysRequired: "En az bir veritabanı seçmelisiniz.",
  colDatabase: "Database",
  colDatabaseKey: "Database Key",
  colDatabaseLabel: "Database Label",

  restoreWarningFairCrm:
    "FAIR CRM verileri geri yüklenecek. Bu işlem mevcut fair_crm veritabanını siler ve seçili backup dosyasındaki veriyle yeniden yükler. Bu işlem geri alınamaz.",
  restoreWarningKyroxCore:
    "DİKKAT: KYROX Core veritabanı geri yüklenecek. Kullanıcılar, roller, yetkiler ve oturum verileri değişecektir. Tüm platform oturumları etkilenebilir. Bu işlem geri alınamaz.",
  restoreWarningKyroxCoreStrong:
    "KYROX Core restore, platform genelinde kimlik ve yetkilendirme verilerini değiştirir. Production ortamında ekstra dikkat gerektirir.",
  restoreUploadDatabaseLabel: "Hedef veritabanı",
  restoreUploadWarningFairCrm:
    "Bu işlem FAIR CRM veritabanını seçilen dosyadaki verilerle değiştirir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreUploadWarningKyroxCore:
    "DİKKAT: Bu işlem KYROX Core veritabanını değiştirir. Kullanıcılar, roller ve yetkiler etkilenir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreJobColSourceDatabase: "Source DB",
  restoreJobColTargetDatabase: "Target DB",

  colName: "Backup Name",
  colFormat: "Format",
  colCreatedAt: "Created At",
  colCreatedBy: "Created By",
  colSize: "Size",
  colDuration: "Duration",
  colStatus: "Status",
  colNotes: "Notes",
  colActions: "Actions",

  actionDownload: "Download",
  actionDetails: "Details",
  actionRestore: "Restore",
  actionDelete: "Delete",
  restoreDisabledHint: "Yalnızca tamamlanmış .dump yedekleri geri yüklenebilir",
  restoreNotDumpHint: "Yalnızca PostgreSQL .dump formatı geri yüklenebilir",
  deleteDisabledHint: "Silme bu sürümde devre dışı",

  restoreFromFile: "Dosyadan Geri Yükle",
  restoreFromFileTitle: "Dosyadan Geri Yükle",
  restoreFromFileWarning:
    "Bu işlem mevcut veritabanını seçilen dosyadaki verilerle değiştirir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreDatabaseTitle: "Restore Database",
  deleteBackupTitle: "Yedeği Sil",
  restoreWarning:
    "Bu işlem mevcut veritabanını siler ve seçili backup dosyasındaki veriyle yeniden yükler. Bu işlem geri alınamaz. Devam etmeden önce mevcut veritabanının yedeğini aldığınızdan emin olun.",
  deleteBackupWarning: "Bu backup dosyası kalıcı olarak silinecek.",
  restoreConfirmLabel: "Onay için RESTORE yazın",
  restoreConfirmHelp: "Bu alan büyük/küçük harfe duyarlıdır.",
  deleteConfirmLabel: "Onay için DELETE yazın",
  restoreConfirmPlaceholder: "RESTORE",
  deleteConfirmPlaceholder: "DELETE",
  restoreDatabaseButton: "Restore Database",
  restoreFromFileButton: "Dosyadan Geri Yükle",
  restoreUploadLabel: "Backup dosyası",
  restoreUploadPickButton: "Dosya Seç",
  restoreUploadNoFileSelected: "Dosya seçilmedi",
  restoreUploadHint: "Yalnızca PostgreSQL custom format (.dump) dosyaları kabul edilir.",
  restoreAcknowledge:
    "Mevcut veritabanının silineceğini ve seçilen dosyadan geri yükleneceğini anlıyorum.",
  restoreFileSizeLabel: "Dosya boyutu",
  restoreSuccess:
    "Geri yükleme işi oluşturuldu. Bakım scripti çalıştırılmalı; durum otomatik takip ediliyor.",
  restoreSuccessWithRunner:
    "Geri yükleme işi oluşturuldu ve arka planda başlatıldı. Durum otomatik takip ediliyor.",
  restoreError: "Geri yükleme başlatılamadı.",
  restoreJobPollSuccess: "Geri yükleme tamamlandı.",
  restoreJobPollFailed: "Geri yükleme başarısız oldu.",
  restoreJobTracking: "Geri yükleme işi takip ediliyor…",
  restoreJobTrackingQueued:
    "Geri yükleme kuyrukta. Bakım scripti çalıştırılınca durum güncellenecek: .\\scripts\\dev\\run-restore-job.ps1 -RestoreJobId \"{jobId}\"",
  restoreJobTrackingRunning: "Geri yükleme çalışıyor…",
  deleteSuccess: "Yedek silindi.",
  deleteError: "Yedek silinemedi.",
  restoreJobManualHint:
    "Gerçek restore işlemi bakım scripti ile yapılır. Dev: $env:ALLOW_RESTORE=\"true\"; .\\scripts\\dev\\run-restore-job.ps1 -RestoreJobId \"<job-id>\". FAIR_CRM_DATABASE_RESTORE_ENABLED=true ve ALLOW_RESTORE=true ise dev API runner'ı otomatik başlatabilir.",

  restoreJobsTitle: "Restore Jobs",
  restoreJobsSubtitle: "Geri yükleme istekleri ve bakım scripti durumu",
  restoreJobColStatus: "Status",
  restoreJobColSource: "Source",
  restoreJobColFile: "Backup/File",
  restoreJobColRequestedAt: "Requested At",
  restoreJobColRequestedBy: "Requested By",
  restoreJobColNotes: "Notes",
  restoreJobSourceExisting: "Existing Backup",
  restoreJobSourceUpload: "Uploaded File",
  restoreJobStatusQueued: "Kuyrukta",
  restoreJobStatusRunning: "Çalışıyor",
  restoreJobStatusSucceeded: "Başarılı",
  restoreJobStatusFailed: "Başarısız",
  restoreJobDetailsTitle: "Restore Job Detayları",
  restoreJobDetailLogPath: "Log path",
  restoreJobDetailStartedAt: "Started At",
  restoreJobDetailCompletedAt: "Completed At",
  restoreJobDetailRunnerCommand: "Runner Command",
  restoreJobDetailError: "Error",
  restoreJobLiveLogTitle: "Live Log",
  restoreJobLiveLogPolling: "Canlı güncelleniyor…",
  restoreJobLiveLogLoading: "Log yükleniyor…",
  restoreJobLiveLogMissing:
    "Restore runner henüz başlamamış veya log dosyası oluşmamış.",
  restoreJobLiveLogEmpty: "Log dosyası boş.",
  restoreJobLiveLogTruncated: "Log çok büyük; yalnızca son kısım gösteriliyor.",
  restoreJobDetailBackupSummary: "Backup özeti",
  restoreJobEmpty: "Henüz restore job yok.",
  restoreJobEmptyDescription: "Bir backup veya dosya yükleyerek geri yükleme isteği oluşturun.",
  restoreJobLoadError: "Restore job listesi yüklenemedi.",

  statusRunning: "Running",
  statusCompleted: "Completed",
  statusFailed: "Failed",

  stagePreparing: "Preparing",
  stageDumping: "Dumping Database",
  stageCompressing: "Compressing",
  stageCompleted: "Completed",
  stageFailed: "Failed",

  backupsEmpty: "Henüz yedek alınmadı.",
  backupsEmptyDescription: "Import veya migration öncesi güvenli bir snapshot oluşturmak için yeni yedek başlatın.",
  loadError: "Yedekler yüklenemedi.",
  createError: "Yedek başlatılamadı.",
  downloadError: "Yedek indirilemedi.",
  detailsTitle: "Yedek Detayları",
  detailChecksum: "Checksum (SHA-256)",
  detailFormat: "Format",
  detailManifest: "Manifest",
  detailDownloadCount: "İndirme sayısı",
  detailError: "Hata",
  detailProgress: "İlerleme",
  backupStarting: "Yedek arka planda başlatıldı…",

  smtpTitle: "SMTP Hesapları",
  smtpSubtitle: "Kuruluşunuz için giden e-posta SMTP hesaplarını yönetin",
  smtpNewAccount: "+ SMTP Hesabı Ekle",
  smtpEditAccount: "SMTP Hesabını Düzenle",
  smtpLoadError: "SMTP hesapları yüklenemedi.",
  smtpCreateError: "SMTP hesabı oluşturulamadı.",
  smtpUpdateError: "SMTP hesabı güncellenemedi.",
  smtpDeleteError: "SMTP hesabı silinemedi.",
  smtpSetDefaultError: "Varsayılan SMTP hesabı ayarlanamadı.",
  smtpCreateSuccess: "SMTP hesabı oluşturuldu.",
  smtpUpdateSuccess: "SMTP hesabı güncellendi.",
  smtpDeleteSuccess: "SMTP hesabı silindi.",
  smtpSetDefaultSuccess: "Varsayılan SMTP hesabı güncellendi.",
  smtpDeleteTitle: "SMTP Hesabını Sil",
  smtpDeleteConfirm: "{name} SMTP hesabını silmek istediğinize emin misiniz?",
  smtpEmptyTitle: "Henüz SMTP hesabı yok",
  smtpEmptyDescription: "Kuruluşunuz için giden e-posta gönderimi tanımlamak üzere bir SMTP hesabı ekleyin.",
  smtpSaving: "Kaydediliyor…",
  smtpPermissionDenied: "SMTP hesaplarını görüntüleme yetkiniz yok.",
  smtpUnexpectedPasswordField: "Beklenmeyen güvenlik yanıtı alındı.",
  smtpDefaultBadge: "Varsayılan",
  smtpActiveBadge: "Aktif",
  smtpInactiveBadge: "Pasif",
  smtpPasswordConfigured: "Şifre tanımlı",
  smtpPasswordMissing: "Şifre yok",
  smtpPasswordConfiguredHint: "Şifre tanımlı. Değiştirmek için yeni değer girin; boş bırakırsanız mevcut şifre korunur.",
  smtpPasswordKeepPlaceholder: "Boş bırakılırsa mevcut şifre korunur",
  smtpActionEdit: "Düzenle",
  smtpActionSetDefault: "Default yap",
  smtpSetDefaultInactiveHint: "Pasif SMTP hesabı varsayılan yapılamaz",
  smtpAlreadyDefaultHint: "Bu hesap zaten varsayılan",
  smtpColName: "SMTP Adı",
  smtpColFromName: "From Name",
  smtpColFromEmail: "From Email",
  smtpColHost: "Host",
  smtpColPort: "Port",
  smtpColEncryption: "Şifreleme",
  smtpColActive: "Durum",
  smtpColHasPassword: "Şifre",
  smtpColUpdatedAt: "Güncellendi",
  smtpFieldName: "SMTP adı",
  smtpFieldFromEmail: "From email",
  smtpFieldFromName: "From name",
  smtpFieldHost: "Host",
  smtpFieldPort: "Port",
  smtpFieldUsername: "Kullanıcı adı",
  smtpFieldPassword: "Şifre",
  smtpFieldEncryption: "Şifreleme türü",
  smtpFieldIsDefault: "Varsayılan SMTP hesabı",
  smtpFieldIsActive: "Aktif",
  smtpSectionGeneral: "Genel Bilgiler",
  smtpSectionServer: "Sunucu Ayarları",
  smtpSectionAuth: "Kimlik Doğrulama",
  smtpSectionStatus: "Durum",
  smtpSectionTestMail: "Test Mail",
  smtpFieldTestRecipient: "Test mail alıcısı",
  smtpActionTestMail: "Test Et",
  smtpTestMailSuccess: "Test e-postası gönderildi.",
  smtpTestMailError: "Test e-postası gönderilemedi.",
  smtpTestMailSending: "Test mail gönderiliyor…",
  smtpHintSslPort: "SSL genelde 465 portu ile kullanılır.",
  smtpHintStarttlsPort: "STARTTLS genelde 587 portu ile kullanılır.",
  smtpHintUseStarttlsOn587:
    "587 kullanıyorsanız şifreleme türü olarak ssl değil starttls seçin.",
  smtpHintUseSslOn465: "465 kullanıyorsanız şifreleme türü olarak ssl seçin.",
  smtpConfigWarningTitle: "Port / şifreleme uyarısı",

  navMailTemplates: "Mail Şablonları",
  mailTemplatesTitle: "Mail Şablonları",
  mailTemplatesSubtitle: "Kuruluşunuz için e-posta şablonlarını yönetin",
  mailTemplatesNew: "+ Mail Şablonu Ekle",
  mailTemplatesEdit: "Mail Şablonunu Düzenle",
  mailTemplatesPreview: "Şablon Önizleme",
  mailTemplatesLoadError: "Mail şablonları yüklenemedi.",
  mailTemplatesCreateError: "Mail şablonu oluşturulamadı.",
  mailTemplatesUpdateError: "Mail şablonu güncellenemedi.",
  mailTemplatesDeleteError: "Mail şablonu silinemedi.",
  mailTemplatesRenderError: "Şablon önizlemesi oluşturulamadı.",
  mailTemplatesCreateSuccess: "Mail şablonu oluşturuldu.",
  mailTemplatesUpdateSuccess: "Mail şablonu güncellendi.",
  mailTemplatesDeleteSuccess: "Mail şablonu silindi.",
  mailTemplatesDeleteTitle: "Mail Şablonunu Sil",
  mailTemplatesDeleteConfirm: "Bu mail şablonunu silmek istediğinize emin misiniz?",
  mailTemplatesEmptyTitle: "Henüz mail şablonu yok",
  mailTemplatesEmptyDescription: "Kuruluşunuz için tekrar kullanılabilir e-posta şablonları oluşturun.",
  mailTemplatesPermissionDenied: "Mail şablonlarını görüntüleme yetkiniz yok.",
  mailTemplatesSaving: "Kaydediliyor…",
  mailTemplatesDefaultHint:
    "Bu şablonu varsayılan yaparsanız aynı tür ve dildeki diğer varsayılan şablon varsayılan olmaktan çıkar.",
  mailTemplatesColName: "Ad",
  mailTemplatesColKey: "Key",
  mailTemplatesColType: "Tür",
  mailTemplatesColLanguage: "Dil",
  mailTemplatesColActive: "Durum",
  mailTemplatesColDefault: "Varsayılan",
  mailTemplatesColUpdatedAt: "Güncellendi",
  mailTemplatesActionEdit: "Düzenle",
  mailTemplatesActionPreview: "Önizle",
  mailTemplatesActionDelete: "Sil",
  mailTemplatesActiveBadge: "Aktif",
  mailTemplatesInactiveBadge: "Pasif",
  mailTemplatesDefaultBadge: "Varsayılan",
  mailTemplatesFilterType: "Tür filtresi",
  mailTemplatesFilterLanguage: "Dil filtresi",
  mailTemplatesFilterActive: "Durum filtresi",
  mailTemplatesFilterDefault: "Varsayılan filtresi",
  mailTemplatesFilterAll: "Tümü",
  mailTemplatesFilterActiveOnly: "Yalnızca aktif",
  mailTemplatesFilterInactiveOnly: "Yalnızca pasif",
  mailTemplatesFilterDefaultOnly: "Yalnızca varsayılan",
  mailTemplatesFilterNonDefault: "Varsayılan olmayan",
  mailTemplatesSectionGeneral: "Genel Bilgiler",
  mailTemplatesSectionContent: "İçerik",
  mailTemplatesSectionStatus: "Durum",
  mailTemplatesSectionPreview: "Önizleme",
  mailTemplatesFieldName: "Şablon adı",
  mailTemplatesFieldKey: "Key",
  mailTemplatesFieldSubject: "Konu (subject)",
  mailTemplatesFieldBodyHtml: "HTML gövde",
  mailTemplatesFieldBodyText: "Düz metin gövde",
  mailTemplatesFieldType: "Şablon türü",
  mailTemplatesFieldLanguage: "Dil",
  mailTemplatesFieldVariablesSchema: "variables_schema (JSON)",
  mailTemplatesFieldIsActive: "Aktif",
  mailTemplatesFieldIsDefault: "Varsayılan şablon",
  mailTemplatesFieldSampleVariables: "Örnek değişkenler (JSON)",
  mailTemplatesRenderAction: "Önizleme Oluştur",
  mailTemplatesRenderRunning: "Önizleme oluşturuluyor…",
  mailTemplatesRenderedSubject: "Render edilmiş konu",
  mailTemplatesRenderedBodyHtml: "Render edilmiş HTML",
  mailTemplatesRenderedBodyText: "Render edilmiş düz metin",
  mailTemplatesKeyHint: "Örnek: welcome_email, fair_reminder_tr",
  mailTemplatesActionsMenu: "İşlemler",
  mailTemplatesActionTestEmail: "Test email gönder",
  mailTemplatesActionSetDefault: "Varsayılan yap",
  mailTemplatesSetDefaultTitle: "Varsayılan Şablon",
  mailTemplatesSetDefaultConfirm: "Bu şablonu varsayılan yapmak istediğinize emin misiniz?",
  mailTemplatesSetDefaultSuccess: "Mail şablonu varsayılan olarak ayarlandı.",
  mailTemplatesSetDefaultError: "Mail şablonu varsayılan yapılamadı.",
  mailTemplatesSetDefaultInactiveHint: "Pasif şablon varsayılan yapılamaz.",
  mailTemplatesAlreadyDefaultHint: "Bu şablon zaten varsayılan.",
  mailTemplatesTestEmailTitle: "Test Email Gönder",
  mailTemplatesTestEmailSection: "Test Gönderimi",
  mailTemplatesTestEmailRecipient: "Test mail alıcısı",
  mailTemplatesTestEmailRecipientRequired: "Test mail alıcısı zorunludur.",
  mailTemplatesTestEmailSmtpAccount: "SMTP hesabı",
  mailTemplatesTestEmailDefaultSmtp: "Varsayılan SMTP hesabı",
  mailTemplatesTestEmailSubmit: "Test Mail Gönder",
  mailTemplatesTestEmailSending: "Test mail gönderiliyor…",
  mailTemplatesTestEmailSuccess: "Test mail başarıyla gönderildi.",
  mailTemplatesTestEmailError: "Test mail gönderilemedi.",
  mailTemplatesTestEmailLoadSmtpError: "SMTP hesapları yüklenemedi.",
  mailTemplatesTestEmailSubject: "Konu (subject)",
  mailTemplatesTestEmailSubjectRequired: "Konu (subject) zorunludur.",
  mailTemplatesTestEmailPreviewAction: "Önizle",
  mailTemplatesTestEmailPreviewRunning: "Önizleme oluşturuluyor…",
  mailTemplatesTestEmailPreviewSection: "Gönderim Önizlemesi",
  mailTemplatesTestEmailPreviewRequired: "Test mail göndermeden önce önizleme oluşturmalısınız.",
  mailTemplatesTestEmailPreviewStale: "Değişkenler değişti. Lütfen yeniden önizleyin.",
  mailTemplatesTestEmailPreviewRecipient: "Alıcı",
  mailTemplatesTestEmailSendSubject: "Gönderilecek konu",
  mailTemplatesTestEmailSendSubjectHint:
    "Body şablondan render edilir; konu alanındaki değer test mail için override edilir.",
  mailTemplatesTestEmailInvalidEmail: "Geçerli bir test alıcı e-posta adresi girin.",
  mailTemplatesTestEmailRenderPermissionDenied: "Önizleme için render yetkisi gereklidir.",
  mailTemplatesTestEmailEndpointNotFound:
    "Test email endpoint bulunamadı. Backend güncel kodla yeniden başlatılmalı.",

  dataOperationsTitle: "Data Operations",
  dataOperationsSubtitle: "Tek seferlik veya talep üzerine veri bakım işlemleri (yalnızca sistem yöneticileri)",
  navDataOperations: "Data Operations",
  dataOpRun: "Run",
  dataOpRunning: "Running…",
  dataOpLoading: "Yükleniyor…",
  dataOpLoadError: "Data operations yüklenemedi.",
  dataOpRunError: "İşlem başlatılamadı.",
  dataOpDownloadError: "Dosya indirilemedi.",
  dataOpDestructiveConfirm:
    "Bu işlem geri alınamaz veri silme içerir. Devam etmek istediğinize emin misiniz?",
  dataOpColStatus: "Execution Status",
  dataOpColStartedBy: "Started By",
  dataOpColStartedAt: "Started At",
  dataOpColFinishedAt: "Finished At",
  dataOpColLastRun: "Last Run",
  dataOpColResult: "Result",
  dataOpDownloads: "Downloads",
  dataOpStatusQueued: "Queued",
  dataOpStatusRunning: "Running",
  dataOpStatusCompleted: "Completed",
  dataOpStatusFailed: "Failed",
  dataOpResultSuccess: "Success",
  dataOpResultFailed: "Failed",
  dataOpViewResults: "View Results",
  dataOpAnalyzeResultTitle: "Analyze Customers Without Fair",
  dataOpAnalyzeResultSubtitle: "Customer cleanup workflow — step 1 analysis results",
  dataOpBackToOperations: "Back to Data Operations",
  dataOpExportExcel: "Export to Excel",
  dataOpExporting: "Exporting…",
  dataOpExportError: "Excel export failed.",
  dataOpResultNotReady: "Analysis results are not ready yet.",
  dataOpSummaryTotalCustomers: "Total Customers",
  dataOpSummaryCustomersWithFair: "Customers With Fair",
  dataOpSummaryCustomersWithoutFair: "Customers Without Fair",
  dataOpAnalyzeEmptyTitle: "No customers without fair participation",
  dataOpAnalyzeEmptyDescription: "This analysis run did not find any unassigned customers.",
  dataOpColSelection: "Selection",
  dataOpSelectAllOnPage: "Select All",
  dataOpAssignToFair: "Assign Selected to Fair",
  dataOpAssignToFairTitle: "Assign Selected to Fair",
  dataOpAssignToFairDescription: "Create fair participations for the selected customers.",
  dataOpAssignToFairFairLabel: "Fair",
  dataOpAssignToFairFairPlaceholder: "Search fairs…",
  dataOpAssignToFairSelectedCount: "Selected customers",
  dataOpAssignToFairSelectedFair: "Selected fair",
  dataOpAssignToFairFairSelected: "Chosen in selector",
  dataOpAssignToFairFairNotSelected: "Not selected",
  dataOpAssignToFairConfirm: "Assign",
  dataOpAssignToFairAssigning: "Assigning…",
  dataOpAssignToFairError: "Assign to fair failed.",
  dataOpAssignToFairProgress: "Assigning selected customers to fair…",
  dataOpAssignToFairResult: (assigned: number, skipped: number, failed: number) =>
    `Assigned: ${assigned}, skipped: ${skipped}, failed: ${failed}`,
  dataOpDeleteSelected: "Delete Selected",
  dataOpDeleteSelectedTitle: "Delete Selected",
  dataOpDeleteSelectedWarning: "This will physically delete the selected customers from the database.",
  dataOpDeleteSelectedDescription:
    "Only customers with zero fair participations are deleted. Customers that now have fair participation are skipped.",
  dataOpDeleteSelectedCountLabel: "Selected customers",
  dataOpDeleteSelectedConfirm: "Delete",
  dataOpDeleteSelectedDeleting: "Deleting…",
  dataOpDeleteSelectedError: "Delete selected failed.",
  dataOpDeleteSelectedProgress: "Deleting selected customers…",
  dataOpDeleteSelectedResult: (deleted: number, skipped: number, failed: number) =>
    `Deleted: ${deleted}, skipped: ${skipped}, failed: ${failed}`,
  dataOpColCompanyName: "Company Name",
  dataOpColLegalName: "Legal Name",
  dataOpColTradeName: "Trade Name",
  dataOpColCustomerType: "Customer Type",
  dataOpColStatusField: "Status",
  dataOpColPhone: "Phone",
  dataOpColEmail: "Email",
  dataOpColWebsite: "Website",
  dataOpColCity: "City",
  dataOpColCountry: "Country",
  dataOpColCreatedAt: "Created At",
  dataOpColUpdatedAt: "Updated At",
  dataOpDuplicateResultTitle: "Duplicate Customer Analysis",
  dataOpDuplicateResultSubtitle: "Customer groups sharing the same normalized field value",
  dataOpSummaryGroupBy: "Group By",
  dataOpGroupByCompanyName: "Company Name",
  dataOpGroupByEmail: "Email",
  dataOpGroupByWebsite: "Website",
  dataOpGroupByPhone: "Phone",
  dataOpGroupByLabel: "Group by",
  dataOpGroupByRequired: "Choose a grouping field before running analysis.",
  dataOpSummaryDuplicateGroups: "Duplicate Groups",
  dataOpSummaryCustomersInDuplicateGroups: "Customers In Duplicate Groups",
  dataOpDuplicateEmptyTitle: "No duplicate customer groups found",
  dataOpDuplicateEmptyDescription: "This analysis run did not find any duplicate groups.",
  dataOpColDuplicateGroup: "Group Key",
  dataOpColGroupBy: "Group By",
  dataOpColCreatedAtMin: "Earliest Created",
  dataOpColCreatedAtMax: "Latest Created",
  dataOpColMatchScore: "Match Score",
  dataOpColDuplicateReason: "Duplicate Reason",
  dataOpColFairCount: "Fair Count",
  dataOpColFairName: "Fair Name",
  dataOpColFirstFair: "First Fair",
  dataOpDuplicateGroupsTitle: "Duplicate Groups",
  dataOpDuplicateGroupsSubtitle: "Review duplicate groups before merge decisions",
  dataOpDuplicateGroupsSearchPlaceholder: "Search group key or winner...",
  dataOpDuplicateGroupDetailTitle: "Merge Preparation",
  dataOpDuplicateGroupDetailSubtitle: "Select field values from each customer before merging",
  dataOpBackToDuplicateGroups: "Back to Duplicate Groups",
  dataOpColGroupKey: "Group Key",
  dataOpDuplicateGroupMergeNotice:
    "All fair participations from every customer will automatically move to the merged customer. Participations cannot be selected or removed here.",
  dataOpDuplicateGroupSuggestedWinnerBadge: "⭐ Suggested Winner",
  dataOpColCustomerId: "Customer ID",
  dataOpMergeSelectFieldsTitle: "Merge field selection",
  dataOpMergeSelectFieldsHint:
    "Choose one option for single-value fields. Select the values you want to keep for multi-value fields.",
  dataOpMergeCustomers: "Merge Customers",
  dataOpMergeConfirmTitle: "Merge Customers",
  dataOpMergeConfirmMessage:
    "Summary bölümündeki işlemler uygulanacak. Surviving customer dışındaki müşteriler kalıcı olarak silinecek. Onaylıyor musunuz?",
  dataOpMergeConfirmCustomersToDelete: "Silinecek müşteri sayısı",
  dataOpMergeConfirmCustomersToDeleteList: "Customers that will be deleted",
  dataOpMergeConfirmAction: "Merge Customers",
  dataOpMergeExecuting: "Merging customers…",
  dataOpMergeSuccess: "Customers merged successfully.",
  dataOpDuplicateAnalysisStale:
    "This analysis snapshot is out of date after the merge. The list below shows live duplicate groups. Re-run Duplicate Customer Analysis for a fresh full scan.",
  dataOpMergeExecuteError: "Merge failed. Please try again.",
  dataOpMergeChooseDifferentWinner: "Choose Different Winner",
  dataOpMergeCancel: "Cancel",
  dataOpMergeSummaryTitle: "Merge Summary",
  dataOpMergeSummaryLive: "Live",
  dataOpMergeSummaryDraft: "Draft",
  dataOpMergeSummaryPreview: "Preview",
  dataOpMergePreviewPrompt: "Preview updates automatically as you change selections.",
  dataOpMergePreviewLoading: "Building preview…",
  dataOpMergePreviewRefreshing: "Updating preview…",
  dataOpMergePreviewReady: "Preview is valid. You can proceed with merge execute.",
  dataOpSurvivingCustomer: "Surviving Customer",
  dataOpSurvivingParticipations: "Participations",
  dataOpSetAsSurviving: "Set as surviving",
  dataOpSummaryIdentityFields: "Identity Fields",
  dataOpSummarySelectedEmails: "Selected Emails",
  dataOpSummarySelectedPhones: "Selected Phones",
  dataOpSummarySelectedWebsites: "Selected Websites",
  dataOpSummaryParticipations: "Participations",
  dataOpSummaryTotalParticipationRows: "Total Participations",
  dataOpSummaryUniqueFairs: "Unique Fairs",
  dataOpSummaryFairParticipations: "Fair Participations",
  dataOpSummaryParticipationNote:
    "All participation rows will move to the surviving customer.",
  dataOpSummaryMergeResult: "Merge Result",
  dataOpMergeValidationReady: "All validations passed. Ready for merge preview.",
  dataOpMergeDedupNotice:
    "If you select the same value more than once, the system will save only one unique record.",
  dataOpExpandAll: "Expand All",
  dataOpCollapseAll: "Collapse All",
  dataOpExpandCard: "Expand",
  dataOpCollapseCard: "Collapse",
  dataOpSelectAll: "Select All",
  dataOpResetToWinner: "Reset to Winner",
  dataOpCopy: "Copy",
  dataOpCopied: "Copied",
  dataOpCopyCustomerId: "Copy customer ID",
  dataOpPrimary: "Primary",
  dataOpSelectedCommunicationsCount: "Selected communications",
  dataOpColCustomerCount: "Customer Count",
  dataOpColFairNames: "Fair Names",
  dataOpColSuggestedWinner: "Suggested Winner",
  dataOpColMaxMatchScore: "Max Match Score",
  dataOpColDuplicateReasons: "Duplicate Reasons",
  dataOpColReview: "Review",
  dataOpDuplicateGroupMergePolicyTitle: "Future merge policy",
  dataOpDuplicateGroupParticipations: "Fair participations",
  dataOpDuplicateGroupNoParticipations: "No fair participations",
  dataOpColFairYear: "Year",
  dataOpColHall: "Hall",
  dataOpColStand: "Stand",
} as const;

export const DISABLED_ADMIN_NAV_ITEMS = [
  { id: "background-jobs", label: "Background Jobs" },
  { id: "audit-logs", label: "Audit Logs" },
  { id: "health", label: "Health Monitoring" },
  { id: "storage", label: "Storage Management" },
  { id: "maintenance", label: "Maintenance Mode" },
  { id: "scheduler", label: "Scheduler" },
  { id: "disaster-recovery", label: "Disaster Recovery" },
] as const;
