export const adminLabels = {
  moduleTitle: "Admin",
  systemTitle: "System",
  systemSubtitle: "Sistem yönetimi ve operasyon araçları",
  navDatabaseBackups: "Database Backups",
  navSmtpAccounts: "SMTP Hesapları",
  comingSoon: "Yakında",
  comingSoonMessage: "Bu özellik yakında kullanıma sunulacak.",

  backupsTitle: "Database Backups",
  backupsSubtitle: "Disaster recovery, SQL export ve taşınabilir veri paketleri",
  newBackup: "+ New Backup",
  newBackupTitle: "Yeni Veritabanı Yedeği",
  formatLabel: "Format",
  formatPostgresqlDump: "PostgreSQL Native Backup (.dump)",
  formatPostgresqlDumpDesc:
    "Tam geri yükleme için önerilir. En güvenli restore formatıdır.",
  formatPostgresqlSql: "PostgreSQL SQL Script (.sql)",
  formatPostgresqlSqlDesc:
    "PostgreSQL uyumlu düz SQL çıktısıdır. Navicat, DBeaver, DataGrip gibi araçlarda inceleme/import için uygundur.",
  formatUniversalPackage: "Universal Data Package (.zip)",
  formatUniversalPackageDesc:
    "Platform bağımsız JSON + manifest veri paketi. Gelecekte MSSQL, MySQL veya başka CRM sistemlerine migration için kullanılacaktır.",
  formatPostgresqlDumpShort: "DR (.dump)",
  formatPostgresqlSqlShort: "SQL (.sql)",
  formatUniversalPackageShort: "Data Package (.zip)",
  notesLabel: "Açıklama (isteğe bağlı)",
  notesPlaceholder: "Örn: Maktek import testi öncesi",
  notesHint: "Bu yedek neden alındığını not edin.",
  startBackup: "Yedeği Başlat",
  cancel: "İptal",

  colName: "Backup Name",
  colFormat: "Format",
  colCreatedAt: "Created At",
  colCreatedBy: "Created By",
  colSize: "Size",
  colDuration: "Duration",
  colStatus: "Status",
  colNotes: "Notes",
  colActions: "Actions",

  actionDownload: "Download",
  actionDetails: "Details",
  actionRestore: "Restore",
  actionDelete: "Delete",
  restoreDisabledHint: "Restore bu sürümde devre dışı",
  deleteDisabledHint: "Silme bu sürümde devre dışı",

  statusRunning: "Running",
  statusCompleted: "Completed",
  statusFailed: "Failed",

  stagePreparing: "Preparing",
  stageDumping: "Dumping Database",
  stageCompressing: "Compressing",
  stageCompleted: "Completed",
  stageFailed: "Failed",

  backupsEmpty: "Henüz yedek alınmadı.",
  backupsEmptyDescription: "Import veya migration öncesi güvenli bir snapshot oluşturmak için yeni yedek başlatın.",
  loadError: "Yedekler yüklenemedi.",
  createError: "Yedek başlatılamadı.",
  downloadError: "Yedek indirilemedi.",
  detailsTitle: "Yedek Detayları",
  detailChecksum: "Checksum (SHA-256)",
  detailFormat: "Format",
  detailManifest: "Manifest",
  detailDownloadCount: "İndirme sayısı",
  detailError: "Hata",
  detailProgress: "İlerleme",
  backupStarting: "Yedek arka planda başlatıldı…",

  smtpTitle: "SMTP Hesapları",
  smtpSubtitle: "Kuruluşunuz için giden e-posta SMTP hesaplarını yönetin",
  smtpNewAccount: "+ SMTP Hesabı Ekle",
  smtpEditAccount: "SMTP Hesabını Düzenle",
  smtpLoadError: "SMTP hesapları yüklenemedi.",
  smtpCreateError: "SMTP hesabı oluşturulamadı.",
  smtpUpdateError: "SMTP hesabı güncellenemedi.",
  smtpDeleteError: "SMTP hesabı silinemedi.",
  smtpSetDefaultError: "Varsayılan SMTP hesabı ayarlanamadı.",
  smtpCreateSuccess: "SMTP hesabı oluşturuldu.",
  smtpUpdateSuccess: "SMTP hesabı güncellendi.",
  smtpDeleteSuccess: "SMTP hesabı silindi.",
  smtpSetDefaultSuccess: "Varsayılan SMTP hesabı güncellendi.",
  smtpDeleteTitle: "SMTP Hesabını Sil",
  smtpDeleteConfirm: "{name} SMTP hesabını silmek istediğinize emin misiniz?",
  smtpEmptyTitle: "Henüz SMTP hesabı yok",
  smtpEmptyDescription: "Kuruluşunuz için giden e-posta gönderimi tanımlamak üzere bir SMTP hesabı ekleyin.",
  smtpSaving: "Kaydediliyor…",
  smtpPermissionDenied: "SMTP hesaplarını görüntüleme yetkiniz yok.",
  smtpUnexpectedPasswordField: "Beklenmeyen güvenlik yanıtı alındı.",
  smtpDefaultBadge: "Varsayılan",
  smtpActiveBadge: "Aktif",
  smtpInactiveBadge: "Pasif",
  smtpPasswordConfigured: "Şifre tanımlı",
  smtpPasswordMissing: "Şifre yok",
  smtpPasswordConfiguredHint: "Şifre tanımlı. Değiştirmek için yeni değer girin; boş bırakırsanız mevcut şifre korunur.",
  smtpPasswordKeepPlaceholder: "Boş bırakılırsa mevcut şifre korunur",
  smtpActionEdit: "Düzenle",
  smtpActionSetDefault: "Default yap",
  smtpSetDefaultInactiveHint: "Pasif SMTP hesabı varsayılan yapılamaz",
  smtpAlreadyDefaultHint: "Bu hesap zaten varsayılan",
  smtpColName: "SMTP Adı",
  smtpColFromName: "From Name",
  smtpColFromEmail: "From Email",
  smtpColHost: "Host",
  smtpColPort: "Port",
  smtpColEncryption: "Şifreleme",
  smtpColActive: "Durum",
  smtpColHasPassword: "Şifre",
  smtpColUpdatedAt: "Güncellendi",
  smtpFieldName: "SMTP adı",
  smtpFieldFromEmail: "From email",
  smtpFieldFromName: "From name",
  smtpFieldHost: "Host",
  smtpFieldPort: "Port",
  smtpFieldUsername: "Kullanıcı adı",
  smtpFieldPassword: "Şifre",
  smtpFieldEncryption: "Şifreleme türü",
  smtpFieldIsDefault: "Varsayılan SMTP hesabı",
  smtpFieldIsActive: "Aktif",

  dataOperationsTitle: "Data Operations",
  dataOperationsSubtitle: "Tek seferlik veya talep üzerine veri bakım işlemleri (yalnızca sistem yöneticileri)",
  navDataOperations: "Data Operations",
  dataOpRun: "Run",
  dataOpRunning: "Running…",
  dataOpLoading: "Yükleniyor…",
  dataOpLoadError: "Data operations yüklenemedi.",
  dataOpRunError: "İşlem başlatılamadı.",
  dataOpDownloadError: "Dosya indirilemedi.",
  dataOpDestructiveConfirm:
    "Bu işlem geri alınamaz veri silme içerir. Devam etmek istediğinize emin misiniz?",
  dataOpColStatus: "Execution Status",
  dataOpColStartedBy: "Started By",
  dataOpColStartedAt: "Started At",
  dataOpColFinishedAt: "Finished At",
  dataOpColLastRun: "Last Run",
  dataOpColResult: "Result",
  dataOpDownloads: "Downloads",
  dataOpStatusQueued: "Queued",
  dataOpStatusRunning: "Running",
  dataOpStatusCompleted: "Completed",
  dataOpStatusFailed: "Failed",
  dataOpResultSuccess: "Success",
  dataOpResultFailed: "Failed",
  dataOpViewResults: "View Results",
  dataOpAnalyzeResultTitle: "Analyze Customers Without Fair",
  dataOpAnalyzeResultSubtitle: "Customer cleanup workflow — step 1 analysis results",
  dataOpBackToOperations: "Back to Data Operations",
  dataOpExportExcel: "Export to Excel",
  dataOpExporting: "Exporting…",
  dataOpExportError: "Excel export failed.",
  dataOpResultNotReady: "Analysis results are not ready yet.",
  dataOpSummaryTotalCustomers: "Total Customers",
  dataOpSummaryCustomersWithFair: "Customers With Fair",
  dataOpSummaryCustomersWithoutFair: "Customers Without Fair",
  dataOpAnalyzeEmptyTitle: "No customers without fair participation",
  dataOpAnalyzeEmptyDescription: "This analysis run did not find any unassigned customers.",
  dataOpColSelection: "Selection",
  dataOpSelectAllOnPage: "Select All",
  dataOpAssignToFair: "Assign Selected to Fair",
  dataOpAssignToFairTitle: "Assign Selected to Fair",
  dataOpAssignToFairDescription: "Create fair participations for the selected customers.",
  dataOpAssignToFairFairLabel: "Fair",
  dataOpAssignToFairFairPlaceholder: "Search fairs…",
  dataOpAssignToFairSelectedCount: "Selected customers",
  dataOpAssignToFairSelectedFair: "Selected fair",
  dataOpAssignToFairFairSelected: "Chosen in selector",
  dataOpAssignToFairFairNotSelected: "Not selected",
  dataOpAssignToFairConfirm: "Assign",
  dataOpAssignToFairAssigning: "Assigning…",
  dataOpAssignToFairError: "Assign to fair failed.",
  dataOpAssignToFairProgress: "Assigning selected customers to fair…",
  dataOpAssignToFairResult: (assigned: number, skipped: number, failed: number) =>
    `Assigned: ${assigned}, skipped: ${skipped}, failed: ${failed}`,
  dataOpDeleteSelected: "Delete Selected",
  dataOpDeleteSelectedTitle: "Delete Selected",
  dataOpDeleteSelectedWarning: "This will physically delete the selected customers from the database.",
  dataOpDeleteSelectedDescription:
    "Only customers with zero fair participations are deleted. Customers that now have fair participation are skipped.",
  dataOpDeleteSelectedCountLabel: "Selected customers",
  dataOpDeleteSelectedConfirm: "Delete",
  dataOpDeleteSelectedDeleting: "Deleting…",
  dataOpDeleteSelectedError: "Delete selected failed.",
  dataOpDeleteSelectedProgress: "Deleting selected customers…",
  dataOpDeleteSelectedResult: (deleted: number, skipped: number, failed: number) =>
    `Deleted: ${deleted}, skipped: ${skipped}, failed: ${failed}`,
  dataOpColCompanyName: "Company Name",
  dataOpColLegalName: "Legal Name",
  dataOpColTradeName: "Trade Name",
  dataOpColCustomerType: "Customer Type",
  dataOpColStatusField: "Status",
  dataOpColPhone: "Phone",
  dataOpColEmail: "Email",
  dataOpColWebsite: "Website",
  dataOpColCity: "City",
  dataOpColCountry: "Country",
  dataOpColCreatedAt: "Created At",
  dataOpColUpdatedAt: "Updated At",
  dataOpDuplicateResultTitle: "Duplicate Customer Analysis",
  dataOpDuplicateResultSubtitle: "Customer groups sharing the same normalized field value",
  dataOpSummaryGroupBy: "Group By",
  dataOpGroupByCompanyName: "Company Name",
  dataOpGroupByEmail: "Email",
  dataOpGroupByWebsite: "Website",
  dataOpGroupByPhone: "Phone",
  dataOpGroupByLabel: "Group by",
  dataOpGroupByRequired: "Choose a grouping field before running analysis.",
  dataOpSummaryDuplicateGroups: "Duplicate Groups",
  dataOpSummaryCustomersInDuplicateGroups: "Customers In Duplicate Groups",
  dataOpDuplicateEmptyTitle: "No duplicate customer groups found",
  dataOpDuplicateEmptyDescription: "This analysis run did not find any duplicate groups.",
  dataOpColDuplicateGroup: "Group Key",
  dataOpColGroupBy: "Group By",
  dataOpColCreatedAtMin: "Earliest Created",
  dataOpColCreatedAtMax: "Latest Created",
  dataOpColMatchScore: "Match Score",
  dataOpColDuplicateReason: "Duplicate Reason",
  dataOpColFairCount: "Fair Count",
  dataOpColFairName: "Fair Name",
  dataOpColFirstFair: "First Fair",
  dataOpDuplicateGroupsTitle: "Duplicate Groups",
  dataOpDuplicateGroupsSubtitle: "Review duplicate groups before merge decisions",
  dataOpDuplicateGroupsSearchPlaceholder: "Search group key or winner...",
  dataOpDuplicateGroupDetailTitle: "Merge Preparation",
  dataOpDuplicateGroupDetailSubtitle: "Select field values from each customer before merging",
  dataOpBackToDuplicateGroups: "Back to Duplicate Groups",
  dataOpColGroupKey: "Group Key",
  dataOpDuplicateGroupMergeNotice:
    "All fair participations from every customer will automatically move to the merged customer. Participations cannot be selected or removed here.",
  dataOpDuplicateGroupSuggestedWinnerBadge: "⭐ Suggested Winner",
  dataOpColCustomerId: "Customer ID",
  dataOpMergeSelectFieldsTitle: "Merge field selection",
  dataOpMergeSelectFieldsHint:
    "Choose one option for single-value fields. Select the values you want to keep for multi-value fields.",
  dataOpMergeCustomers: "Merge Customers",
  dataOpMergeConfirmTitle: "Merge Customers",
  dataOpMergeConfirmMessage:
    "Summary bölümündeki işlemler uygulanacak. Surviving customer dışındaki müşteriler kalıcı olarak silinecek. Onaylıyor musunuz?",
  dataOpMergeConfirmCustomersToDelete: "Silinecek müşteri sayısı",
  dataOpMergeConfirmCustomersToDeleteList: "Customers that will be deleted",
  dataOpMergeConfirmAction: "Merge Customers",
  dataOpMergeExecuting: "Merging customers…",
  dataOpMergeSuccess: "Customers merged successfully.",
  dataOpDuplicateAnalysisStale:
    "This analysis snapshot is out of date after the merge. The list below shows live duplicate groups. Re-run Duplicate Customer Analysis for a fresh full scan.",
  dataOpMergeExecuteError: "Merge failed. Please try again.",
  dataOpMergeChooseDifferentWinner: "Choose Different Winner",
  dataOpMergeCancel: "Cancel",
  dataOpMergeSummaryTitle: "Merge Summary",
  dataOpMergeSummaryLive: "Live",
  dataOpMergeSummaryDraft: "Draft",
  dataOpMergeSummaryPreview: "Preview",
  dataOpMergePreviewPrompt: "Preview updates automatically as you change selections.",
  dataOpMergePreviewLoading: "Building preview…",
  dataOpMergePreviewRefreshing: "Updating preview…",
  dataOpMergePreviewReady: "Preview is valid. You can proceed with merge execute.",
  dataOpSurvivingCustomer: "Surviving Customer",
  dataOpSurvivingParticipations: "Participations",
  dataOpSetAsSurviving: "Set as surviving",
  dataOpSummaryIdentityFields: "Identity Fields",
  dataOpSummarySelectedEmails: "Selected Emails",
  dataOpSummarySelectedPhones: "Selected Phones",
  dataOpSummarySelectedWebsites: "Selected Websites",
  dataOpSummaryParticipations: "Participations",
  dataOpSummaryTotalParticipationRows: "Total Participations",
  dataOpSummaryUniqueFairs: "Unique Fairs",
  dataOpSummaryFairParticipations: "Fair Participations",
  dataOpSummaryParticipationNote:
    "All participation rows will move to the surviving customer.",
  dataOpSummaryMergeResult: "Merge Result",
  dataOpMergeValidationReady: "All validations passed. Ready for merge preview.",
  dataOpMergeDedupNotice:
    "If you select the same value more than once, the system will save only one unique record.",
  dataOpExpandAll: "Expand All",
  dataOpCollapseAll: "Collapse All",
  dataOpExpandCard: "Expand",
  dataOpCollapseCard: "Collapse",
  dataOpSelectAll: "Select All",
  dataOpResetToWinner: "Reset to Winner",
  dataOpCopy: "Copy",
  dataOpCopied: "Copied",
  dataOpCopyCustomerId: "Copy customer ID",
  dataOpPrimary: "Primary",
  dataOpSelectedCommunicationsCount: "Selected communications",
  dataOpColCustomerCount: "Customer Count",
  dataOpColFairNames: "Fair Names",
  dataOpColSuggestedWinner: "Suggested Winner",
  dataOpColMaxMatchScore: "Max Match Score",
  dataOpColDuplicateReasons: "Duplicate Reasons",
  dataOpColReview: "Review",
  dataOpDuplicateGroupMergePolicyTitle: "Future merge policy",
  dataOpDuplicateGroupParticipations: "Fair participations",
  dataOpDuplicateGroupNoParticipations: "No fair participations",
  dataOpColFairYear: "Year",
  dataOpColHall: "Hall",
  dataOpColStand: "Stand",
} as const;

export const DISABLED_ADMIN_NAV_ITEMS = [
  { id: "background-jobs", label: "Background Jobs" },
  { id: "audit-logs", label: "Audit Logs" },
  { id: "health", label: "Health Monitoring" },
  { id: "storage", label: "Storage Management" },
  { id: "maintenance", label: "Maintenance Mode" },
  { id: "scheduler", label: "Scheduler" },
  { id: "disaster-recovery", label: "Disaster Recovery" },
] as const;
