export const adminLabels = {
  moduleTitle: "Admin",
  systemTitle: "System",
  smtpOperationsTitle: "E-Mail Operations",
  navOperationCapabilities: "Otomasyon Yetenekleri",
  operationCapabilitiesTitle: "Otomasyon Yetenekleri",
  operationCapabilitiesSubtitle: "Otomasyon türü yeteneklerini yönetin",
  operationCapabilitiesTypeLabel: "Otomasyon Türü",
  operationCapabilitiesTypePlaceholder: "Otomasyon türü seçin",
  operationCapabilitiesLoadError: "Otomasyon türleri yüklenemedi.",
  operationCapabilitiesSaveError: "Yetenekler kaydedilemedi.",
  operationCapabilitiesSaveSuccess: "Yetenekler kaydedildi.",
  operationCapabilitiesSave: "Kaydet",
  operationCapabilitiesSaving: "Kaydediliyor…",
  operationCapabilitiesEditTitle: "Otomasyon Yeteneklerini Düzenle",
  operationCapabilitiesEmptyTitle: "Henüz otomasyon türü yok",
  operationCapabilitiesEmptyDescription:
    "Veritabanında listelenecek otomasyon türü bulunamadı.",
  operationCapabilitiesColName: "Otomasyon",
  operationCapabilitiesColActive: "Aktif",
  operationCapabilitiesColCapabilities: "Yetenekler",
  operationCapabilitiesColUpdatedAt: "Güncelleme",
  operationCapabilitiesColActions: "İşlem",
  operationCapabilitiesActionEdit: "Düzenle",
  operationCapabilitiesNameLabel: "Otomasyon Adı",
  operationCapabilitiesActiveLabel: "Aktif",
  operationCapabilitiesActiveHint: "Pasif türler yeni otomasyon oluşturmada kullanılmaz.",
  operationCapabilitiesActiveBadge: "Aktif",
  operationCapabilitiesInactiveBadge: "Pasif",
  operationCapabilitySupportsPause: "Duraklatılabilir",
  operationCapabilitySupportsResume: "Devam Ettirilebilir",
  operationCapabilitySupportsRetry: "Tekrar Denenebilir",
  operationCapabilitySupportsSchedule: "Zamanlanabilir",
  operationCapabilitySupportsItems: "Item / Kayıt Bazlı Çalışır",
  operationCapabilitySupportsPauseShort: "Duraklat",
  operationCapabilitySupportsResumeShort: "Devam Et",
  operationCapabilitySupportsRetryShort: "Retry",
  operationCapabilitySupportsScheduleShort: "Zamanla",
  operationCapabilitySupportsItemsShort: "Item Bazlı",
  operationCapabilitySupportsPauseHint: "Çalışan otomasyon geçici olarak durdurulabilir.",
  operationCapabilitySupportsResumeHint:
    "Duraklatılmış otomasyon kaldığı yerden devam ettirilebilir.",
  operationCapabilitySupportsRetryHint: "Başarısız otomasyon yeniden çalıştırılabilir.",
  operationCapabilitySupportsScheduleHint:
    "Otomasyon ileri bir tarih/saat için planlanabilir.",
  operationCapabilitySupportsItemsHint:
    "Otomasyon kayıtları/item’ları ayrı ayrı takip ederek çalışır.",
  navMailOperations: "Merkezi Mail Operasyonları",
  mailOperationsTitle: "Merkezi Mail Operasyonları",
  mailOperationsSubtitle: "Tüm mail gönderim operasyonlarını merkezi olarak görüntüleyin",
  mailOperationsExport: "Export",
  mailOperationsExportSoon: "Export özelliği yakında eklenecek",
  mailOperationsEmptyTitle: "Henüz mail operasyonu kaydı yok",
  mailOperationsEmptyDescription:
    "Henüz kayıt yok. SMTP test veya diğer mail gönderimleri tamamlandıkça operasyonlar burada listelenir.",
  mailOperationsLoadError: "Mail operasyonları yüklenemedi.",
  mailOperationsFilterSearch: "Ara",
  mailOperationsFilterSearchPlaceholder: "Müşteri, alıcı e-posta veya konu...",
  mailOperationsFilterStatus: "Durum",
  mailOperationsFilterSource: "Kaynak / Tip",
  mailOperationsFilterSmtp: "SMTP Hesabı",
  mailOperationsFilterFair: "Fuar",
  mailOperationsFilterDateFrom: "Başlangıç",
  mailOperationsFilterDateTo: "Bitiş",
  mailOperationsFilterAll: "Tümü",
  mailOperationsColDate: "Tarih",
  mailOperationsColSource: "Kaynak / Tip",
  mailOperationsColFair: "Fuar",
  mailOperationsColCustomer: "Müşteri",
  mailOperationsColRecipientEmail: "Alıcı Email",
  mailOperationsColSmtpAccount: "E-Mail hesabı",
  mailOperationsColTemplate: "Şablon",
  mailOperationsColSubject: "Konu",
  mailOperationsColStatus: "Status",
  mailOperationsColError: "Hata Mesajı",
  mailOperationsColProviderMessageId: "Provider Mesaj ID",
  mailOperationsColProviderStatus: "Provider Durumu",
  mailOperationsColActions: "İşlem",
  mailOperationsDemoBanner:
    "Örnek veriler gösteriliyor. Merkezi mail operasyonları API entegrasyonu sonraki aşamada eklenecek.",
  mailOperationsActionsMenuLabel: "İşlemler",
  mailOperationsDetailTitle: "Mail Operasyon Detayı",
  mailOperationsLogsTitle: "Teknik Süreç Logları",
  mailOperationsErrorTitle: "Hata Detayı",
  mailOperationsRetryTitle: "Maili Yeniden Dene",
  mailOperationsRetryMessage:
    "Bu başarısız mail tekrar gönderilecek. Devam edilsin mi?",
  mailOperationsRetrySuccess: "Mail yeniden gönderildi.",
  mailOperationsRetryFailed: "Mail yeniden gönderilemedi.",
  mailOperationsRetryInProgress: "Yeniden gönderiliyor…",
  mailOperationsCancelTitle: "Maili İptal Et",
  mailOperationsCancelMessage:
    "Kuyruktaki bu mail operasyonu iptal edilsin mi? (Backend entegrasyonu yakında)",
  mailOperationsRetryTodo: "Retry işlemi henüz bağlanmadı (TODO).",
  mailOperationsCancelTodo: "İptal işlemi henüz bağlanmadı (TODO).",
  mailOperationsCopySuccess: "Mail operasyon özeti panoya kopyalandı.",
  mailOperationsCopyError: "Panoya kopyalanamadı.",
  mailOperationsNoLogs: "Log kaydı bulunmuyor.",
  mailOperationsNoError: "Hata mesajı yok.",
  mailOperationsStatusLabels: {
    queued: "Kuyrukta",
    sending: "Gönderiliyor",
    sent: "Gönderildi",
    failed: "Başarısız",
    cancelled: "İptal Edildi",
    skipped: "Atlandı",
  },
  mailOperationsSourceLabels: {
    smtp_test: "SMTP Test",
    template_test: "Şablon Test",
    fair_bulk_email: "Fuar Toplu Mail",
    system_notification: "Sistem Bildirimi",
    manual_email: "Manuel E-posta",
    manual_task_mail: "Manuel Görev Maili",
  },
  mailOperationsActionLabels: {
    detail: "Detay",
    logs: "Logları Gör",
    copy: "Kopyala",
    retry: "Tekrar Gönder",
    error_detail: "Hata Detayı",
    cancel: "İptal Et",
  },
  systemSubtitle: "Sistem yönetimi ve operasyon araçları",
  navDatabaseBackups: "Database Backups",
  navSmtpAccounts: "E-Mail Hesapları",
  comingSoon: "Yakında",
  comingSoonMessage: "Bu özellik yakında kullanıma sunulacak.",

  backupsTitle: "Database Backups",
  backupsSubtitle: "Disaster recovery, SQL export ve taşınabilir veri paketleri",
  newBackup: "+ New Backup",
  newBackupTitle: "Yeni Veritabanı Yedeği",
  formatLabel: "Format",
  formatPostgresqlDump: "PostgreSQL Native Backup (.dump)",
  formatPostgresqlDumpDesc:
    "Tam geri yükleme için önerilir. En güvenli restore formatıdır.",
  formatPostgresqlSql: "PostgreSQL SQL Script (.sql)",
  formatPostgresqlSqlDesc:
    "PostgreSQL uyumlu düz SQL çıktısıdır. Navicat, DBeaver, DataGrip gibi araçlarda inceleme/import için uygundur.",
  formatUniversalPackage: "Universal Data Package (.zip)",
  formatUniversalPackageDesc:
    "Platform bağımsız JSON + manifest veri paketi. Gelecekte MSSQL, MySQL veya başka CRM sistemlerine migration için kullanılacaktır.",
  formatPostgresqlDumpShort: "DR (.dump)",
  formatPostgresqlSqlShort: "SQL (.sql)",
  formatUniversalPackageShort: "Data Package (.zip)",
  notesLabel: "Açıklama",
  notesPlaceholder: "Örn: Maktek import testi öncesi",
  notesHint: "İsteğe bağlı. Bu yedek neden alındığını not edin.",
  startBackup: "Yedeği Başlat",
  cancel: "İptal",

  databaseKeysLabel: "Yedeklenecek veritabanları",
  databaseKeyKyroxCore: "KYROX Core",
  databaseKeyFairCrm: "FAIR CRM",
  databaseKeyKyroxCoreDesc: "Kullanıcılar, organizasyonlar, roller, yetkiler ve oturum tabloları",
  databaseKeyFairCrmDesc: "Müşteriler, fuarlar, contacts, görevler, SMTP ve CRM verileri",
  databaseKeysRequired: "En az bir veritabanı seçmelisiniz.",
  colDatabase: "Database",
  colDatabaseKey: "Database Key",
  colDatabaseLabel: "Database Label",

  restoreWarningFairCrm:
    "FAIR CRM verileri geri yüklenecek. Bu işlem mevcut fair_crm veritabanını siler ve seçili backup dosyasındaki veriyle yeniden yükler. Bu işlem geri alınamaz.",
  restoreWarningKyroxCore:
    "DİKKAT: KYROX Core veritabanı geri yüklenecek. Kullanıcılar, roller, yetkiler ve oturum verileri değişecektir. Tüm platform oturumları etkilenebilir. Bu işlem geri alınamaz.",
  restoreWarningKyroxCoreStrong:
    "KYROX Core restore, platform genelinde kimlik ve yetkilendirme verilerini değiştirir. Production ortamında ekstra dikkat gerektirir.",
  restoreUploadDatabaseLabel: "Hedef veritabanı",
  restoreUploadWarningFairCrm:
    "Bu işlem FAIR CRM veritabanını seçilen dosyadaki verilerle değiştirir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreUploadWarningKyroxCore:
    "DİKKAT: Bu işlem KYROX Core veritabanını değiştirir. Kullanıcılar, roller ve yetkiler etkilenir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreJobColSourceDatabase: "Source DB",
  restoreJobColTargetDatabase: "Target DB",

  colName: "Backup Name",
  colFormat: "Format",
  colCreatedAt: "Created At",
  colCreatedBy: "Created By",
  colSize: "Size",
  colDuration: "Duration",
  colStatus: "Status",
  colNotes: "Notes",
  colActions: "Actions",

  actionDownload: "Download",
  actionDetails: "Details",
  actionRestore: "Restore",
  actionDelete: "Delete",
  restoreDisabledHint: "Yalnızca tamamlanmış .dump yedekleri geri yüklenebilir",
  restoreNotDumpHint: "Yalnızca PostgreSQL .dump formatı geri yüklenebilir",
  deleteDisabledHint: "Silme bu sürümde devre dışı",

  restoreFromFile: "Dosyadan Geri Yükle",
  restoreFromFileTitle: "Dosyadan Geri Yükle",
  restoreFromFileWarning:
    "Bu işlem mevcut veritabanını seçilen dosyadaki verilerle değiştirir. Devam etmeden önce güncel yedek aldığınızdan emin olun.",
  restoreDatabaseTitle: "Restore Database",
  deleteBackupTitle: "Yedeği Sil",
  restoreWarning:
    "Bu işlem mevcut veritabanını siler ve seçili backup dosyasındaki veriyle yeniden yükler. Bu işlem geri alınamaz. Devam etmeden önce mevcut veritabanının yedeğini aldığınızdan emin olun.",
  deleteBackupWarning: "Bu backup dosyası kalıcı olarak silinecek.",
  restoreConfirmLabel: "Onay için RESTORE yazın",
  restoreConfirmHelp: "Bu alan büyük/küçük harfe duyarlıdır.",
  deleteConfirmLabel: "Onay için DELETE yazın",
  restoreConfirmPlaceholder: "RESTORE",
  deleteConfirmPlaceholder: "DELETE",
  restoreDatabaseButton: "Restore Database",
  restoreFromFileButton: "Dosyadan Geri Yükle",
  restoreUploadLabel: "Backup dosyası",
  restoreUploadPickButton: "Dosya Seç",
  restoreUploadNoFileSelected: "Dosya seçilmedi",
  restoreUploadHint: "Yalnızca PostgreSQL custom format (.dump) dosyaları kabul edilir.",
  restoreAcknowledge:
    "Mevcut veritabanının silineceğini ve seçilen dosyadan geri yükleneceğini anlıyorum.",
  restoreFileSizeLabel: "Dosya boyutu",
  restoreSuccess:
    "Geri yükleme işi oluşturuldu. Bakım scripti çalıştırılmalı; durum otomatik takip ediliyor.",
  restoreSuccessWithRunner:
    "Geri yükleme işi oluşturuldu ve arka planda başlatıldı. Durum otomatik takip ediliyor.",
  restoreError: "Geri yükleme başlatılamadı.",
  restoreJobPollSuccess: "Geri yükleme tamamlandı.",
  restoreJobPollFailed: "Geri yükleme başarısız oldu.",
  restoreJobTracking: "Geri yükleme işi takip ediliyor…",
  restoreJobTrackingQueued:
    "Geri yükleme kuyrukta. Bakım scripti çalıştırılınca durum güncellenecek: .\\scripts\\dev\\run-restore-job.ps1 -RestoreJobId \"{jobId}\"",
  restoreJobTrackingRunning: "Geri yükleme çalışıyor…",
  deleteSuccess: "Yedek silindi.",
  deleteError: "Yedek silinemedi.",
  restoreJobManualHint:
    "Gerçek restore işlemi bakım scripti ile yapılır. Dev: $env:ALLOW_RESTORE=\"true\"; .\\scripts\\dev\\run-restore-job.ps1 -RestoreJobId \"<job-id>\". FAIR_CRM_DATABASE_RESTORE_ENABLED=true ve ALLOW_RESTORE=true ise dev API runner'ı otomatik başlatabilir.",

  restoreJobsTitle: "Restore Jobs",
  restoreJobsSubtitle: "Geri yükleme istekleri ve bakım scripti durumu",
  restoreJobColStatus: "Status",
  restoreJobColSource: "Source",
  restoreJobColFile: "Backup/File",
  restoreJobColRequestedAt: "Requested At",
  restoreJobColRequestedBy: "Requested By",
  restoreJobColNotes: "Notes",
  restoreJobSourceExisting: "Existing Backup",
  restoreJobSourceUpload: "Uploaded File",
  restoreJobStatusQueued: "Kuyrukta",
  restoreJobStatusRunning: "Çalışıyor",
  restoreJobStatusSucceeded: "Başarılı",
  restoreJobStatusFailed: "Başarısız",
  restoreJobDetailsTitle: "Restore Job Detayları",
  restoreJobDetailLogPath: "Log path",
  restoreJobDetailStartedAt: "Started At",
  restoreJobDetailCompletedAt: "Completed At",
  restoreJobDetailRunnerCommand: "Runner Command",
  restoreJobDetailError: "Error",
  restoreJobLiveLogTitle: "Live Log",
  restoreJobLiveLogPolling: "Canlı güncelleniyor…",
  restoreJobLiveLogLoading: "Log yükleniyor…",
  restoreJobLiveLogMissing:
    "Restore runner henüz başlamamış veya log dosyası oluşmamış.",
  restoreJobLiveLogEmpty: "Log dosyası boş.",
  restoreJobLiveLogTruncated: "Log çok büyük; yalnızca son kısım gösteriliyor.",
  restoreJobDetailBackupSummary: "Backup özeti",
  restoreJobEmpty: "Henüz restore job yok.",
  restoreJobEmptyDescription: "Bir backup veya dosya yükleyerek geri yükleme isteği oluşturun.",
  restoreJobLoadError: "Restore job listesi yüklenemedi.",

  statusRunning: "Running",
  statusCompleted: "Completed",
  statusFailed: "Failed",

  stagePreparing: "Preparing",
  stageDumping: "Dumping Database",
  stageCompressing: "Compressing",
  stageCompleted: "Completed",
  stageFailed: "Failed",

  backupsEmpty: "Henüz yedek alınmadı.",
  backupsEmptyDescription: "Import veya migration öncesi güvenli bir snapshot oluşturmak için yeni yedek başlatın.",
  loadError: "Yedekler yüklenemedi.",
  createError: "Yedek başlatılamadı.",
  downloadError: "Yedek indirilemedi.",
  detailsTitle: "Yedek Detayları",
  detailChecksum: "Checksum (SHA-256)",
  detailFormat: "Format",
  detailManifest: "Manifest",
  detailDownloadCount: "İndirme sayısı",
  detailError: "Hata",
  detailProgress: "İlerleme",
  backupStarting: "Yedek arka planda başlatıldı…",

  smtpTitle: "E-Mail Hesapları",
  smtpSubtitle: "Kuruluşunuz için giden e-posta gönderim hesaplarını yönetin",
  smtpNewAccount: "Hesap Ekle",
  smtpCreateModalTitle: "Gönderim Hesabı Ekle",
  smtpEditAccount: "Gönderim Hesabını Düzenle",
  smtpLoadError: "E-mail hesapları yüklenemedi.",
  smtpCreateError: "E-mail hesabı oluşturulamadı.",
  smtpUpdateError: "E-mail hesabı güncellenemedi.",
  smtpDeleteError: "E-mail hesabı silinemedi.",
  smtpSetDefaultError: "Varsayılan gönderim hesabı ayarlanamadı.",
  smtpCreateSuccess: "Gönderim hesabı oluşturuldu.",
  smtpUpdateSuccess: "Gönderim hesabı güncellendi.",
  smtpDeleteSuccess: "Gönderim hesabı silindi.",
  smtpSetDefaultSuccess: "Varsayılan gönderim hesabı güncellendi.",
  smtpDeleteTitle: "Gönderim Hesabını Sil",
  smtpDeleteConfirm: "{name} gönderim hesabını silmek istediğinize emin misiniz?",
  smtpDeleteDefaultConfirm:
    "{name} varsayılan gönderim hesabıdır. Silindiğinde varsayılan, varsa başka bir aktif hesaba aktarılır; aksi halde sistemde varsayılan hesap kalmayabilir. Silmek istediğinize emin misiniz?",
  smtpDeactivateDefaultTitle: "Varsayılan Hesabı Pasifleştir",
  smtpDeactivateDefaultConfirm:
    "Bu hesap varsayılan gönderim hesabıdır. Pasifleştirildiğinde varsayılan, varsa başka bir aktif hesaba aktarılır; aksi halde sistemde varsayılan hesap kalmayabilir. Devam etmek istiyor musunuz?",
  smtpDeactivateDefaultConfirmLabel: "Pasifleştir",
  smtpFieldMaxDeliveryAttempts: "Başarısız Gönderim Deneme Sayısı",
  smtpMaxDeliveryAttemptsInvalid: "Başarısız gönderim deneme sayısı 1–5 arasında olmalıdır.",
  emailAccountPickerLabel: "Gönderim hesabı",
  emailAccountPickerEmpty: "Aktif gönderim hesabı yok",
  smtpEmptyTitle: "Henüz gönderim hesabı yok",
  smtpEmptyDescription:
    "Kuruluşunuz için giden e-posta gönderimi tanımlamak üzere bir hesap ekleyin.",
  smtpSaving: "Kaydediliyor…",
  smtpPermissionDenied: "E-mail hesaplarını görüntüleme yetkiniz yok.",
  smtpUnexpectedPasswordField: "Beklenmeyen güvenlik yanıtı alındı.",
  smtpDefaultBadge: "Varsayılan",
  smtpActiveBadge: "Aktif",
  smtpInactiveBadge: "Pasif",
  smtpPasswordConfigured: "Şifre tanımlı",
  smtpPasswordMissing: "Şifre yok",
  smtpPasswordConfiguredHint:
    "Şifre tanımlı. Değiştirmek için yeni değer girin; boş bırakırsanız mevcut şifre korunur.",
  smtpPasswordKeepPlaceholder: "Boş bırakılırsa mevcut şifre korunur",
  smtpActionEdit: "Düzenle",
  smtpActionSetDefault: "Default yap",
  smtpSetDefaultInactiveHint: "Pasif hesap varsayılan yapılamaz",
  smtpAlreadyDefaultHint: "Bu hesap zaten varsayılan",
  smtpColName: "Hesap Adı",
  smtpColAccountType: "Tür",
  smtpColFromName: "From Name",
  smtpColFromEmail: "From Email",
  smtpColHost: "Sunucu / Provider",
  smtpColPort: "Port",
  smtpColEncryption: "Şifreleme",
  smtpColActive: "Durum",
  smtpColHasPassword: "Şifre",
  smtpColUpdatedAt: "Güncellendi",
  smtpAccountTypeSmtp: "SMTP",
  smtpAccountTypeProvider: "Provider",
  smtpFieldAccountType: "Hesap Türü",
  smtpFieldName: "Hesap adı",
  smtpFieldFromEmail: "From email",
  smtpFieldFromName: "From name",
  smtpFieldHost: "Host",
  smtpFieldPort: "Port",
  smtpFieldUsername: "Kullanıcı adı",
  smtpFieldPassword: "Şifre",
  smtpFieldEncryption: "Şifreleme türü",
  smtpFieldIsDefault: "Varsayılan gönderim hesabı",
  smtpFieldIsActive: "Aktif",
  smtpSectionAccountType: "Hesap Türü",
  smtpSectionGeneral: "Genel Bilgiler",
  smtpSectionServer: "Sunucu Ayarları",
  smtpSectionAuth: "Kimlik Doğrulama",
  smtpSectionStatus: "Durum",
  smtpSectionTestMail: "Test Mail",
  smtpSectionProvider: "Provider Ayarları",
  smtpSectionErrorPolicy: "Hata Politikası",
  smtpProviderUnavailableTitle: "Provider hesapları henüz kullanılamıyor",
  smtpProviderUnavailableDescription:
    "Provider gönderim hesapları sonraki aşamada eklenecek. Şimdilik yalnızca SMTP hesabı oluşturabilirsiniz.",
  smtpProviderSaveDisabledHint: "Provider hesabı bu aşamada kaydedilemez.",
  smtpProviderLoadError: "Provider listesi yüklenemedi.",
  smtpProviderKeyRequired: "Bir provider seçin.",
  smtpProviderNameRequired: "Hesap adı zorunludur.",
  smtpProviderDefinitionMissing: "Seçilen provider tanımı bulunamadı.",
  smtpProviderFieldRequired: "{field} zorunludur.",
  smtpProviderFieldInvalidEmail: "{field} geçerli bir e-posta adresi olmalıdır.",
  smtpProviderFieldProvider: "Provider",
  smtpProviderSelectPlaceholder: "Provider seçin",
  smtpProviderSecretConfiguredHint:
    "Gizli alan tanımlı. Değiştirmek için yeni değer girin; boş bırakırsanız mevcut değer korunur.",
  smtpProviderSecretKeepPlaceholder: "Boş bırakılırsa mevcut değer korunur",
  smtpErrorPolicyIdentifiersLabel: "Hata kodları / tanımlayıcılar",
  smtpErrorPolicyIdentifiersHint: "Virgülle ayırın (örn. 401, 403, 429).",
  smtpErrorPolicyActionLabel: "Aksiyon",
  smtpErrorPolicyCategoryAccount: "Hesap hataları (ACCOUNT_ERROR)",
  smtpErrorPolicyCategoryDelivery: "Teslimat hataları (DELIVERY_ERROR)",
  smtpErrorPolicyCategoryMessage: "Mesaj hataları (MESSAGE_ERROR)",
  smtpErrorPolicyActionFail: "Başarısız say",
  smtpErrorPolicyActionDeactivateAndFail: "Hesabı pasifleştir ve başarısız say",
  smtpErrorPolicyActionRecordAndFail: "Kaydet ve başarısız say",
  smtpErrorPolicyActionAutoRetry: "Otomatik yeniden dene",
  smtpErrorPolicyActionSkip: "Mesajı atla",
  smtpErrorPolicyInvalidAction: "Geçersiz hata politikası aksiyonu.",
  smtpErrorPolicyDuplicateIdentifier:
    "Hata tanımlayıcısı \"{identifier}\" birden fazla gruba ait olamaz.",
  smtpFieldTestRecipient: "Test mail alıcısı",
  smtpActionTestMail: "Test Et",
  smtpTestMailSuccess: "Test e-postası gönderildi.",
  smtpTestMailError: "Test e-postası gönderilemedi.",
  smtpTestMailSending: "Test mail gönderiliyor…",
  smtpHintSslPort: "SSL genelde 465 portu ile kullanılır.",
  smtpHintStarttlsPort: "STARTTLS genelde 587 portu ile kullanılır.",
  smtpHintUseStarttlsOn587:
    "587 kullanıyorsanız şifreleme türü olarak ssl değil starttls seçin.",
  smtpHintUseSslOn465: "465 kullanıyorsanız şifreleme türü olarak ssl seçin.",
  smtpConfigWarningTitle: "Port / şifreleme uyarısı",

  navMailTemplates: "Mail Şablonları",
  mailTemplatesTitle: "Mail Şablonları",
  mailTemplatesSubtitle: "Kuruluşunuz için e-posta şablonlarını yönetin",
  mailTemplatesNew: "+ Mail Şablonu Ekle",
  mailTemplatesEdit: "Mail Şablonunu Düzenle",
  mailTemplatesPreview: "Şablon Önizleme",
  mailTemplatesLoadError: "Mail şablonları yüklenemedi.",
  mailTemplatesCreateError: "Mail şablonu oluşturulamadı.",
  mailTemplatesUpdateError: "Mail şablonu güncellenemedi.",
  mailTemplatesDeleteError: "Mail şablonu silinemedi.",
  mailTemplatesRenderError: "Şablon önizlemesi oluşturulamadı.",
  mailTemplatesCreateSuccess: "Mail şablonu oluşturuldu.",
  mailTemplatesUpdateSuccess: "Mail şablonu güncellendi.",
  mailTemplatesDeleteSuccess: "Mail şablonu silindi.",
  mailTemplatesDeleteTitle: "Mail Şablonunu Sil",
  mailTemplatesDeleteConfirm: "Bu mail şablonunu silmek istediğinize emin misiniz?",
  mailTemplatesEmptyTitle: "Henüz mail şablonu yok",
  mailTemplatesEmptyDescription: "Kuruluşunuz için tekrar kullanılabilir e-posta şablonları oluşturun.",
  mailTemplatesPermissionDenied: "Mail şablonlarını görüntüleme yetkiniz yok.",
  mailTemplatesSaving: "Kaydediliyor…",
  mailTemplatesDefaultHint:
    "Bu şablonu varsayılan yaparsanız aynı tür ve dildeki diğer varsayılan şablon varsayılan olmaktan çıkar.",
  mailTemplatesColName: "Ad",
  mailTemplatesColKey: "Key",
  mailTemplatesColType: "Tür",
  mailTemplatesColLanguage: "Dil",
  mailTemplatesColActive: "Durum",
  mailTemplatesColDefault: "Varsayılan",
  mailTemplatesColUpdatedAt: "Güncellendi",
  mailTemplatesActionEdit: "Düzenle",
  mailTemplatesActionPreview: "Önizle",
  mailTemplatesActionDelete: "Sil",
  mailTemplatesActiveBadge: "Aktif",
  mailTemplatesInactiveBadge: "Pasif",
  mailTemplatesDefaultBadge: "Varsayılan",
  mailTemplatesFilterType: "Tür filtresi",
  mailTemplatesFilterLanguage: "Dil filtresi",
  mailTemplatesFilterActive: "Durum filtresi",
  mailTemplatesFilterDefault: "Varsayılan filtresi",
  mailTemplatesFilterAll: "Tümü",
  mailTemplatesFilterActiveOnly: "Yalnızca aktif",
  mailTemplatesFilterInactiveOnly: "Yalnızca pasif",
  mailTemplatesFilterDefaultOnly: "Yalnızca varsayılan",
  mailTemplatesFilterNonDefault: "Varsayılan olmayan",
  mailTemplatesSectionGeneral: "Genel Bilgiler",
  mailTemplatesSectionContent: "İçerik",
  mailTemplatesSectionStatus: "Durum",
  mailTemplatesSectionPreview: "Önizleme",
  mailTemplatesFieldName: "Şablon adı",
  mailTemplatesFieldKey: "Key",
  mailTemplatesFieldSubject: "Konu (subject)",
  mailTemplatesFieldBodyHtml: "HTML gövde",
  mailTemplatesFieldBodyText: "Düz metin gövde",
  mailTemplatesFieldType: "Şablon türü",
  mailTemplatesFieldLanguage: "Dil",
  mailTemplatesFieldVariablesSchema: "variables_schema (JSON)",
  mailTemplatesFieldIsActive: "Aktif",
  mailTemplatesFieldIsDefault: "Varsayılan şablon",
  mailTemplatesFieldSampleVariables: "Örnek değişkenler (JSON)",
  mailTemplatesRenderAction: "Önizleme Oluştur",
  mailTemplatesRenderRunning: "Önizleme oluşturuluyor…",
  mailTemplatesRenderedSubject: "Render edilmiş konu",
  mailTemplatesRenderedBodyHtml: "Render edilmiş HTML",
  mailTemplatesRenderedBodyText: "Render edilmiş düz metin",
  mailTemplatesKeyHint: "Örnek: welcome_email, fair_reminder_tr",
  mailTemplatesActionsMenu: "İşlemler",
  mailTemplatesActionTestEmail: "Test email gönder",
  mailTemplatesActionSetDefault: "Varsayılan yap",
  mailTemplatesSetDefaultTitle: "Varsayılan Şablon",
  mailTemplatesSetDefaultConfirm: "Bu şablonu varsayılan yapmak istediğinize emin misiniz?",
  mailTemplatesSetDefaultSuccess: "Mail şablonu varsayılan olarak ayarlandı.",
  mailTemplatesSetDefaultError: "Mail şablonu varsayılan yapılamadı.",
  mailTemplatesSetDefaultInactiveHint: "Pasif şablon varsayılan yapılamaz.",
  mailTemplatesAlreadyDefaultHint: "Bu şablon zaten varsayılan.",
  mailTemplatesTestEmailTitle: "Test Email Gönder",
  mailTemplatesTestEmailSection: "Test Gönderimi",
  mailTemplatesTestEmailRecipient: "Test mail alıcısı",
  mailTemplatesTestEmailRecipientRequired: "Test mail alıcısı zorunludur.",
  mailTemplatesTestEmailSmtpAccount: "E-Mail hesabı",
  mailTemplatesTestEmailDefaultSmtp: "Varsayılan E-Mail hesabı",
  mailTemplatesTestEmailSubmit: "Test Mail Gönder",
  mailTemplatesTestEmailSending: "Test mail gönderiliyor…",
  mailTemplatesTestEmailSuccess: "Test mail başarıyla gönderildi.",
  mailTemplatesTestEmailError: "Test mail gönderilemedi.",
  mailTemplatesTestEmailLoadSmtpError: "SMTP hesapları yüklenemedi.",
  mailTemplatesTestEmailSubject: "Konu (subject)",
  mailTemplatesTestEmailSubjectRequired: "Konu (subject) zorunludur.",
  mailTemplatesTestEmailPreviewAction: "Önizle",
  mailTemplatesTestEmailPreviewRunning: "Önizleme oluşturuluyor…",
  mailTemplatesTestEmailPreviewSection: "Gönderim Önizlemesi",
  mailTemplatesTestEmailPreviewRequired: "Test mail göndermeden önce önizleme oluşturmalısınız.",
  mailTemplatesTestEmailPreviewStale: "Değişkenler değişti. Lütfen yeniden önizleyin.",
  mailTemplatesTestEmailPreviewRecipient: "Alıcı",
  mailTemplatesTestEmailSendSubject: "Gönderilecek konu",
  mailTemplatesTestEmailSendSubjectHint:
    "Body şablondan render edilir; konu alanındaki değer test mail için override edilir.",
  mailTemplatesTestEmailInvalidEmail: "Geçerli bir test alıcı e-posta adresi girin.",
  mailTemplatesTestEmailRenderPermissionDenied: "Önizleme için render yetkisi gereklidir.",
  mailTemplatesTestEmailEndpointNotFound:
    "Test email endpoint bulunamadı. Backend güncel kodla yeniden başlatılmalı.",

  dataOperationsTitle: "Data Operations",
  dataOperationsSubtitle: "Tek seferlik veya talep üzerine veri bakım işlemleri (yalnızca sistem yöneticileri)",
  navDataOperations: "Data Operations",
  dataOpRun: "Run",
  dataOpRunning: "Running…",
  dataOpLoading: "Yükleniyor…",
  dataOpDuplicateGroupsLoading: "Duplicate grupları yükleniyor…",
  dataOpDuplicateGroupDetailLoading: "Grup detayları yükleniyor…",
  dataOpAnalyzeRunLoading: "Analiz sonuçları yükleniyor…",
  dataOpLoadError: "Data operations yüklenemedi.",
  dataOpRunError: "İşlem başlatılamadı.",
  dataOpDownloadError: "Dosya indirilemedi.",
  dataOpDestructiveConfirm:
    "Bu işlem geri alınamaz veri silme içerir. Devam etmek istediğinize emin misiniz?",
  dataOpColStatus: "Execution Status",
  dataOpColStartedBy: "Started By",
  dataOpColStartedAt: "Started At",
  dataOpColFinishedAt: "Finished At",
  dataOpColLastRun: "Last Run",
  dataOpColResult: "Result",
  dataOpDownloads: "Downloads",
  dataOpStatusQueued: "Queued",
  dataOpStatusRunning: "Running",
  dataOpStatusCompleted: "Completed",
  dataOpStatusFailed: "Failed",
  dataOpResultSuccess: "Success",
  dataOpResultFailed: "Failed",
  dataOpViewResults: "View Results",
  dataOpAnalyzeResultTitle: "Fuarsız Müşteri Analizi",
  dataOpAnalyzeResultSubtitle: "Fuar katılımı olmayan müşterilerin analiz sonuçları",
  dataOpBackToOperations: "Duplicate Kontrolüne Dön",
  dataOpExportExcel: "Excel'e Aktar",
  dataOpExporting: "Dışa aktarılıyor…",
  dataOpExportError: "Excel dışa aktarımı başarısız oldu.",
  dataOpResultNotReady: "Analiz sonuçları henüz hazır değil.",
  dataOpSummaryTotalCustomers: "Toplam Müşteri",
  dataOpSummaryCustomersWithFair: "Fuarı Olan Müşteriler",
  dataOpSummaryCustomersWithoutFair: "Fuarsız Müşteriler",
  dataOpAnalyzeEmptyTitle: "Fuar katılımı olmayan müşteri bulunamadı",
  dataOpAnalyzeEmptyDescription: "Bu analiz çalışmasında atanmamış müşteri bulunamadı.",
  dataOpColSelection: "Seçim",
  dataOpSelectAllOnPage: "Tümünü Seç",
  dataOpAssignToFair: "Seçilenleri Fuara Ata",
  dataOpAssignToFairTitle: "Seçilenleri Fuara Ata",
  dataOpAssignToFairDescription: "Seçilen müşteriler için fuar katılımı oluşturur.",
  dataOpAssignToFairFairLabel: "Fuar",
  dataOpAssignToFairFairPlaceholder: "Fuar ara…",
  dataOpAssignToFairSelectedCount: "Seçilen müşteri",
  dataOpAssignToFairSelectedFair: "Seçilen fuar",
  dataOpAssignToFairFairSelected: "Seçicide seçildi",
  dataOpAssignToFairFairNotSelected: "Seçilmedi",
  dataOpAssignToFairConfirm: "Ata",
  dataOpAssignToFairAssigning: "Atanıyor…",
  dataOpAssignToFairError: "Fuara atama başarısız oldu.",
  dataOpAssignToFairProgress: "Seçilen müşteriler fuara atanıyor…",
  dataOpAssignToFairResult: (assigned: number, skipped: number, failed: number) =>
    `Atanan: ${assigned}, atlanan: ${skipped}, başarısız: ${failed}`,
  dataOpDeleteSelected: "Seçilenleri Sil",
  dataOpDeleteSelectedTitle: "Seçilenleri Sil",
  dataOpDeleteSelectedWarning: "Seçilen müşteriler veritabanından kalıcı olarak silinecek.",
  dataOpDeleteSelectedDescription:
    "Yalnızca fuar katılımı olmayan müşteriler silinir. Artık fuar katılımı olanlar atlanır.",
  dataOpDeleteSelectedCountLabel: "Seçilen müşteri",
  dataOpDeleteSelectedConfirm: "Sil",
  dataOpDeleteSelectedDeleting: "Siliniyor…",
  dataOpDeleteSelectedError: "Seçilenleri silme başarısız oldu.",
  dataOpDeleteSelectedProgress: "Seçilen müşteriler siliniyor…",
  dataOpDeleteSelectedResult: (deleted: number, skipped: number, failed: number) =>
    `Silinen: ${deleted}, atlanan: ${skipped}, başarısız: ${failed}`,
  dataOpColCompanyName: "Firma Adı",
  dataOpColLegalName: "Unvan",
  dataOpColTradeName: "Ticari Unvan",
  dataOpColCustomerType: "Müşteri Tipi",
  dataOpColStatusField: "Durum",
  dataOpColPhone: "Telefon",
  dataOpColEmail: "E-posta",
  dataOpColWebsite: "Web Sitesi",
  dataOpColCity: "Şehir",
  dataOpColCountry: "Ülke",
  dataOpColCreatedAt: "Oluşturulma",
  dataOpColUpdatedAt: "Güncellenme",
  dataOpDuplicateResultTitle: "Duplicate Müşteri Analizi",
  dataOpDuplicateResultSubtitle: "Aynı normalize alan değerini paylaşan müşteri grupları",
  dataOpSummaryGroupBy: "Gruplama Alanı",
  dataOpGroupByCompanyName: "Firma Adı",
  dataOpGroupByEmail: "E-posta",
  dataOpGroupByWebsite: "Web Sitesi",
  dataOpGroupByPhone: "Telefon",
  dataOpGroupByLabel: "Grupla",
  dataOpFairFilterLabel: "Fuar",
  dataOpFairFilterAll: "Tüm Fuarlar",
  dataOpSummaryFairFilter: "Fuar",
  dataOpSummaryAllFairs: "Tüm Fuarlar",
  dataOpGroupByRequired: "Analizi çalıştırmadan önce bir gruplama alanı seçin.",
  dataOpSummaryDuplicateGroups: "Duplicate Grupları",
  dataOpSummaryCustomersInDuplicateGroups: "Duplicate Gruplarındaki Müşteriler",
  dataOpDuplicateEmptyTitle: "Duplicate müşteri grubu bulunamadı",
  dataOpDuplicateEmptyDescription: "Bu analiz çalışmasında duplicate grup bulunamadı.",
  dataOpColDuplicateGroup: "Grup Anahtarı",
  dataOpColGroupBy: "Gruplama Alanı",
  dataOpColCreatedAtMin: "En Erken Oluşturma",
  dataOpColCreatedAtMax: "En Geç Oluşturma",
  dataOpColMatchScore: "Eşleşme Skoru",
  dataOpColDuplicateReason: "Duplicate Nedeni",
  dataOpColFairCount: "Fuar Sayısı",
  dataOpColFairName: "Fuar Adı",
  dataOpColFirstFair: "İlk Fuar",
  dataOpDuplicateGroupsTitle: "Duplicate Grupları",
  dataOpDuplicateGroupsSubtitle: "Birleştirme kararından önce duplicate gruplarını inceleyin",
  dataOpDuplicateGroupsSearchPlaceholder: "Grup anahtarı veya önerilen kayıt ara…",
  dataOpDuplicateGroupDetailTitle: "Birleştirme Hazırlığı",
  dataOpDuplicateGroupDetailSubtitle: "Birleştirmeden önce her müşteriden alan değerlerini seçin",
  dataOpBackToDuplicateGroups: "Duplicate Gruplarına Dön",
  dataOpColGroupKey: "Grup Anahtarı",
  dataOpDuplicateGroupMergeNotice:
    "Tüm müşterilerin fuar katılımları otomatik olarak birleştirilen müşteriye taşınır. Katılımlar burada seçilemez veya kaldırılamaz.",
  dataOpDuplicateGroupSuggestedWinnerBadge: "⭐ Önerilen Kayıt",
  dataOpColCustomerId: "Müşteri ID",
  dataOpMergeSelectFieldsTitle: "Birleştirme alan seçimi",
  dataOpMergeSelectFieldsHint:
    "Tek değerli alanlar için bir seçenek belirleyin. Çok değerli alanlarda korumak istediğiniz değerleri seçin.",
  dataOpMergeCustomers: "Müşterileri Birleştir",
  dataOpMergeConfirmTitle: "Müşterileri Birleştir",
  dataOpMergeConfirmMessage:
    "Özet bölümündeki işlemler uygulanacak. Surviving customer dışındaki müşteriler kalıcı olarak silinecek. Onaylıyor musunuz?",
  dataOpMergeConfirmCustomersToDelete: "Silinecek müşteri sayısı",
  dataOpMergeConfirmCustomersToDeleteList: "Silinecek müşteriler",
  dataOpMergeConfirmAction: "Müşterileri Birleştir",
  dataOpMergeExecuting: "Müşteriler birleştiriliyor…",
  dataOpMergeSuccess: "Müşteriler başarıyla birleştirildi.",
  dataOpDuplicateAnalysisStale:
    "Birleştirme sonrası bu analiz anlık görüntüsü güncelliğini yitirdi. Aşağıdaki liste canlı duplicate gruplarını gösterir. Tam tarama için Duplicate Müşteri Analizi’ni yeniden çalıştırın.",
  dataOpMergeExecuteError: "Birleştirme başarısız oldu. Lütfen tekrar deneyin.",
  dataOpMergeChooseDifferentWinner: "Farklı Kayıt Seç",
  dataOpMergeCancel: "İptal",
  dataOpMergeSummaryTitle: "Birleştirme Özeti",
  dataOpMergeSummaryLive: "Canlı",
  dataOpMergeSummaryDraft: "Taslak",
  dataOpMergeSummaryPreview: "Önizleme",
  dataOpMergePreviewPrompt: "Seçimler değiştikçe önizleme otomatik güncellenir.",
  dataOpMergePreviewLoading: "Önizleme oluşturuluyor…",
  dataOpMergePreviewRefreshing: "Önizleme güncelleniyor…",
  dataOpMergePreviewReady: "Önizleme geçerli. Birleştirmeye devam edebilirsiniz.",
  dataOpSurvivingCustomer: "Kalacak Müşteri",
  dataOpSurvivingParticipations: "Katılımlar",
  dataOpSetAsSurviving: "Kalacak olarak ayarla",
  dataOpSummaryIdentityFields: "Kimlik Alanları",
  dataOpSummarySelectedEmails: "Seçilen E-postalar",
  dataOpSummarySelectedPhones: "Seçilen Telefonlar",
  dataOpSummarySelectedWebsites: "Seçilen Web Siteleri",
  dataOpSummaryParticipations: "Katılımlar",
  dataOpSummaryTotalParticipationRows: "Toplam Katılım",
  dataOpSummaryUniqueFairs: "Benzersiz Fuarlar",
  dataOpSummaryFairParticipations: "Fuar Katılımları",
  dataOpSummaryParticipationNote:
    "Tüm katılım satırları kalacak müşteriye taşınır.",
  dataOpSummaryMergeResult: "Birleştirme Sonucu",
  dataOpMergeValidationReady: "Tüm doğrulamalar geçti. Birleştirme önizlemesine hazır.",
  dataOpMergeDedupNotice:
    "Aynı değeri birden fazla kez seçerseniz sistem yalnızca tek benzersiz kaydı saklar.",
  dataOpExpandAll: "Tümünü Genişlet",
  dataOpCollapseAll: "Tümünü Daralt",
  dataOpExpandCard: "Genişlet",
  dataOpCollapseCard: "Daralt",
  dataOpSelectAll: "Tümünü Seç",
  dataOpResetToWinner: "Önerilene Sıfırla",
  dataOpCopy: "Kopyala",
  dataOpCopied: "Kopyalandı",
  dataOpCopyCustomerId: "Müşteri ID’sini kopyala",
  dataOpPrimary: "Birincil",
  dataOpSelectedCommunicationsCount: "Seçilen iletişimler",
  dataOpColCustomerCount: "Müşteri Sayısı",
  dataOpColFairNames: "Fuar Adları",
  dataOpColSuggestedWinner: "Önerilen Kayıt",
  dataOpColMaxMatchScore: "Maks. Eşleşme Skoru",
  dataOpColDuplicateReasons: "Duplicate Nedenleri",
  dataOpColReview: "İncele",
  dataOpDuplicateGroupMergePolicyTitle: "Birleştirme politikası",
  dataOpDuplicateGroupParticipations: "Fuar katılımları",
  dataOpDuplicateGroupNoParticipations: "Fuar katılımı yok",
  dataOpColFairYear: "Yıl",
  dataOpColHall: "Salon",
  dataOpColStand: "Stand",
} as const;

export const DISABLED_ADMIN_NAV_ITEMS = [
  { id: "background-jobs", label: "Background Jobs" },
  { id: "audit-logs", label: "Audit Logs" },
  { id: "health", label: "Health Monitoring" },
  { id: "storage", label: "Storage Management" },
  { id: "maintenance", label: "Maintenance Mode" },
  { id: "scheduler", label: "Scheduler" },
  { id: "disaster-recovery", label: "Disaster Recovery" },
] as const;
