export const authLabels = {
  pageTitle: "Giriş",
  email: "E-posta",
  password: "Şifre",
  submit: "Giriş Yap",
  submitting: "Giriş yapılıyor…",
  emailRequired: "E-posta adresi gerekli.",
  passwordRequired: "Şifre gerekli.",
  invalidCredentials: "E-posta veya şifre hatalı.",
  invalidInput: "Geçersiz giriş bilgileri.",
  loginFailed: "Giriş başarısız. Lütfen tekrar deneyin.",
  networkError: "Kimlik doğrulama sunucusuna ulaşılamadı. KYROX Core çalışıyor mu?",
  subtitle: "Devam etmek için hesabınızla giriş yapın.",
  userMenuLabel: "Kullanıcı menüsü",
  logout: "Çıkış Yap",
  loggingOut: "Çıkış yapılıyor…",
  organization: "Organizasyon",

  organizationName: "Organizasyon adı",
  organizationNameRequired: "Organizasyon adı gerekli.",
  newPassword: "Yeni şifre",
  newPasswordRequired: "Yeni şifre gerekli.",
  confirmPassword: "Yeni şifreyi tekrar girin",
  confirmPasswordRequired: "Şifre tekrarı gerekli.",
  passwordMismatch: "Şifreler eşleşmiyor.",
  passwordPolicyHint: "Şifreniz en az 12, en fazla 255 karakter olmalıdır.",
  tokenMissing: "Bu bağlantıda gerekli güvenlik anahtarı bulunmuyor. Lütfen e-postadaki bağlantıyı yeniden açın.",
  requestFailed: "İşlem tamamlanamadı. Lütfen tekrar deneyin.",
  backToLogin: "Giriş ekranına dön",

  signupTitle: "Hesap oluştur",
  signupSubtitle: "Organizasyonunuzu ve ilk yönetici hesabınızı oluşturun.",
  signupSubmit: "Hesabı Oluştur",
  signupSubmitting: "Hesap oluşturuluyor…",
  signupSuccess: "Başvurunuz alındı. Hesabınızı etkinleştirmek için e-postanıza gönderilen bağlantıyı kullanın.",

  activationTitle: "Hesabı etkinleştir",
  activationSubtitle: "Hesabınız için güvenli bir şifre belirleyin.",
  activationSubmit: "Hesabı Etkinleştir",
  activationSubmitting: "Hesap etkinleştiriliyor…",
  activationSuccess: "Hesabınız etkinleştirildi. Artık yeni şifrenizle giriş yapabilirsiniz.",

  forgotPasswordTitle: "Şifremi unuttum",
  forgotPasswordSubtitle: "Hesabınıza ait e-posta adresini girin.",
  forgotPasswordSubmit: "Sıfırlama Bağlantısı Gönder",
  forgotPasswordSubmitting: "İstek gönderiliyor…",
  forgotPasswordSuccess: "Hesap uygunsa şifre sıfırlama bağlantısı e-posta adresinize gönderildi.",

  resetPasswordTitle: "Şifreyi sıfırla",
  resetPasswordSubtitle: "Hesabınız için yeni bir şifre belirleyin.",
  resetPasswordSubmit: "Şifreyi Değiştir",
  resetPasswordSubmitting: "Şifre değiştiriliyor…",
  resetPasswordSuccess: "Şifreniz değiştirildi. Yeni şifrenizle tekrar giriş yapabilirsiniz.",
};
