export const contactLabels = {
  sectionTitle: "İletişim Kişileri",
  newContact: "Yeni Kişi Ekle",
  firstName: "Ad",
  lastName: "Soyad",
  title: "Ünvan",
  department: "Departman",
  email: "E-posta",
  phone: "Telefon",
  mobilePhone: "Cep Telefonu",
  linkedin: "LinkedIn",
  notes: "Notlar",
  isPrimary: "Birincil Kişi",
  isActive: "Aktif",
  save: "Kaydet",
  cancel: "İptal",
  edit: "Düzenle",
  delete: "Sil",
  primaryBadge: "Birincil",
  fullName: "Ad Soyad",
  actions: "İşlemler",
  noContacts: "Bu müşteri için iletişim kişisi bulunamadı.",
  deleteConfirm: "Bu iletişim kişisini silmek istediğinize emin misiniz?",
  deleteError: "Silme işlemi başarısız.",
  loadError: "İletişim kişileri yüklenemedi.",
  createError: "Kişi eklenemedi.",
  updateError: "Kişi güncellenemedi.",
  firstNameRequired: "Ad zorunludur.",
  lastNameRequired: "Soyad zorunludur.",
  emailInvalid: "Geçerli bir e-posta adresi girin.",
  contactSectionPerson: "Kişi Bilgileri",
  contactSectionContact: "İletişim Bilgileri",
  contactSectionSocial: "Sosyal / İş Profili",
  contactSectionStatus: "Durum / Notlar",
  contactSectionConsent: "İletişim İzinleri",
  emailSendAllowed: "Email Gönder",
  smsSendAllowed: "SMS Gönder",
  customerEmailConsentBlockedHint:
    "Customer email izni kapalı olduğu için contact'a mail gönderilmez.",
  customerSmsConsentBlockedHint:
    "Customer SMS izni kapalı olduğu için contact'a SMS gönderilmez.",
  editContact: "Kişi Düzenle",
  backToCustomers: "Müşterilere Dön",
  customerDetail: "Müşteri Detayı",
  tabOverview: "Genel Bilgiler",
  tabContacts: "İletişim Kişileri",
} as const;
