export const costItemsLabels = {
  pageTitle: "Maliyet Kalemleri",
  pageSubtitle: "Organization alış ve satış fiyatları. Para birimi TL.",
  actionCreate: "Fiyat ekle",
  actionEdit: "Düzenle",
  actionDelete: "Sil",
  actionSave: "Kaydet",
  actionCancel: "Vazgeç",
  colType: "Tür",
  colItem: "Kalem",
  colUnit: "Hesaplama Birimi",
  colPurchase: "Alış fiyatı (TL)",
  colSale: "Satış fiyatı (TL)",
  colActions: "İşlemler",
  fieldType: "Tür",
  typeItem: "Sahne Elemanı",
  typeManual: "Manuel",
  fieldItem: "Sahne Elemanı",
  fieldName: "Kalem Adı",
  fieldUnit: "Birim",
  fieldPurchase: "Alış fiyatı (TL)",
  fieldSale: "Satış fiyatı (TL)",
  emptyTitle: "Fiyat kaydı yok",
  emptyDescription: "Sahne elemanı seçin veya manuel kalem adı ve birim girin.",
  nameRequired: "Kalem adı boş bırakılamaz.",
  unitRequired: "Birim seçilmelidir.",
  loadError: "Fiyatlar yüklenemedi.",
  saveError: "Fiyat kaydedilemedi.",
  deleteError: "Fiyat silinemedi.",
  deleteTitle: "Fiyat kaydını sil",
  deleteMessage: "Bu maliyet kalemi silinsin mi?",
  purchaseRequired: "Alış fiyatı boş bırakılamaz.",
  purchaseInvalid: "Alış fiyatı 0 veya daha büyük olmalı.",
  saleInvalid: "Satış fiyatı 0 veya daha büyük olmalı.",
  noItems: "Maliyet hesabına açık sahne elemanı yok.",
  noRemainingItems: "Fiyatı girilmemiş sahne elemanı kalmadı.",
  denied: "Bu sayfayı görüntüleme yetkiniz yok.",
};
