export const dashboardLabels = {
  pageTitle: "Dashboard",
  loadError: "Dashboard verisi yüklenemedi.",
  emptyRecentActivitiesTitle: "Henüz aktivite bulunmuyor.",
  emptyRecentActivitiesDescription: "Müşteri aktiviteleri burada listelenecek.",
  emptyFairSummariesTitle: "Fuar özeti bulunmuyor.",
  emptyFairSummariesDescription: "Fuar kaydı eklendiğinde özet burada görünecek.",
  sectionOverview: "Genel Özet",
  sectionTaskSummary: "Görev Özeti",
  sectionRecentActivities: "Son Aktiviteler",
  sectionFairSummary: "Fuar Bazlı Özet",
  sectionMailStatus: "Mail Durumu Özeti",
  sectionQuickActions: "Hızlı Aksiyonlar",
  cardTotalCustomers: "Toplam Müşteri",
  cardTotalFairs: "Toplam Fuar",
  cardOpenTodos: "Açık Görev",
  cardTodayFollowUps: "Bugünkü Takip",
  cardSentMails: "Gönderilen Mail",
  cardFailedMails: "Başarısız Mail",
  taskNotStarted: "Yapılmadı",
  taskInFollowUp: "Takipte",
  taskClosed: "Konu Kapandı",
  taskOverdueFollowUps: "Geciken Takipler",
  colCustomerName: "Müşteri",
  colActivityType: "Aktivite Tipi",
  colNoteSummary: "Not Özeti",
  colDate: "Tarih",
  colFairName: "Fuar",
  colCustomerCount: "Müşteri",
  colCustomersWithActivity: "Aktivite Girilen",
  colCustomersWithMailSent: "Mail Gönderilen",
  colFailedMailCount: "Başarısız Mail",
  mailQueued: "Kuyrukta",
  mailSending: "Gönderiliyor",
  mailSent: "Gönderildi",
  mailFailed: "Başarısız",
  mailTimeout: "Zaman Aşımı",
  actionNewCustomer: "Yeni Müşteri Ekle",
  actionNewTodo: "Yeni Görev Oluştur",
  actionStartImport: "İçe Aktarım Başlat",
  actionSmtpSettings: "SMTP Ayarları",
  actionGoToTodos: "Görevler Ekranı",
} as const;
