export const dataIntegrationLabels = {
  moduleTitle: "Veri Entegrasyonu",
  moduleSubtitle: "Universal Import Engine — güvenli veri aktarımı",
  navImports: "Import İşleri",
  navNewImport: "Yeni Import",
  navHistory: "Import Geçmişi",
  navTemplates: "Mapping Şablonları",
  navJobs: "İşler",
  navReports: "Raporlar",
  comingSoon: "Yakında",
  comingSoonMessage: "Bu özellik yakında kullanıma sunulacak.",
  importsTitle: "Import İşleri",
  importsEmpty: "Henüz import işi yok.",
  newImport: "Yeni Import",
  colFile: "Dosya",
  colFair: "Fuar",
  colStatus: "Durum",
  colRows: "Satır",
  colCreated: "Oluşturulma",
  colActions: "İşlemler",
  openDetail: "Detay",
  continueBatch: "Devam Et",
  deleteBatch: "Sil",
  deleteBatchTitle: "Import işini kalıcı olarak sil",
  deleteBatchMessage:
    "Bu import işi kalıcı olarak silinecek.\n\nAşağıdaki veriler tamamen kaldırılacaktır:\n\n• Upload edilen Excel dosyası\n• Import Batch\n• Import Rows\n• Analyze sonuçları\n• Decision kayıtları\n• Geçici veriler\n\nBu işlem geri alınamaz.",
  deleteBatchConfirm: "Kalıcı Olarak Sil",
  deleteBatchSuccess: "Import işi başarıyla silindi.",
  sheetTitle: "Sayfa seçimi",
  sheetSubtitle: "Excel dosyasındaki çalışma sayfasını seçin.",
  headerModeTitle: "Başlık modu",
  headerFirstRow: "İlk satır başlık içeriyor",
  headerNoHeader: "Başlık yok",
  headerManualRow: "Başlık satırını ben seçeceğim",
  manualHeaderRowLabel: "Başlık satır numarası (1 tabanlı)",
  applyBackground: "Arka planda uygula",
  applyBackgroundHint: "İşlem arka planda çalışır; bu sayfadan ayrılabilirsiniz.",
  jobRunning: "Import işi çalışıyor…",
  jobCompleted: "Import tamamlandı",
  jobFailed: "Import başarısız",
  jobProgress: "İlerleme",
  viewReport: "Raporu görüntüle",
};

export const DISABLED_NAV_ITEMS = [
  { id: "scrapers", label: "Web Scrapers" },
  { id: "export", label: "Export İşleri" },
  { id: "api", label: "API Entegrasyonları" },
  { id: "erp", label: "ERP Entegrasyonları" },
  { id: "csv", label: "CSV/XML Kaynakları" },
  { id: "sync", label: "Senkronizasyon İşleri" },
  { id: "settings", label: "Entegrasyon Ayarları" },
] as const;
