export const fairLabels = {
  fairs: "Fuarlar",
  newFair: "Yeni Fuar",
  editFair: "Fuar Düzenle",
  archiveConfirm: "Bu fuarı arşivlemek istediğinize emin misiniz?",
  restoreConfirm: "Bu fuarı arşivden çıkarmak istiyor musunuz?",
  restoreSuccess: "Fuar arşivden çıkarıldı.",
  searchPlaceholder: "Fuar ara…",
  noResults: "Fuar bulunamadı.",
  loadError: "Fuarlar yüklenemedi.",
  archiveError: "Arşivleme başarısız.",
  restoreError: "Arşivden çıkarma başarısız.",
  nameRequired: "Fuar adı zorunludur.",
  name: "Fuar Adı",
  organizer: "Organizatör",
  venue: "Mekan",
  start_date: "Başlangıç Tarihi",
  end_date: "Bitiş Tarihi",
  dataIntegration: "Veri Entegrasyonu",
  adapter: "Adapter",
  sourceUrl: "Source URL",
  scraperConfig: "Scraper Config",
  lastImport: "Son Import",
  adapterNone: "Adapter seçilmedi",
  adapterSearchPlaceholder: "Adapter ara…",
  adapterNoResults: "Adapter bulunamadı.",
  adapterLoadError: "Adapter listesi yüklenemedi.",
  sourceUrlRequired: "Adapter seçildiğinde Source URL zorunludur.",
  sourceUrlInvalid: "Source URL geçerli bir http veya https adresi olmalıdır.",
  scraperConfigInvalid: "Scraper Config geçerli bir JSON nesnesi olmalıdır.",
  scraperConfigPlaceholder: '{"pagination": {"page_size": 50}}',
  runScraper: "Çalıştır",
  runScraperSuccess: "Adapter çalıştırması başlatıldı.",
  runScraperError: "Adapter çalıştırılamadı.",
  runScraperRunning: "Çalışıyor…",
} as const;

export const fairStatusLabels: Record<string, string> = {
  planned: "Planlandı",
  active: "Aktif",
  completed: "Tamamlandı",
  cancelled: "İptal Edildi",
  archived: "Arşivlenmiş",
};
