export const fairLabels = {
  fairs: "Fuarlar",
  newFair: "Yeni Fuar",
  editFair: "Fuar Düzenle",
  archiveConfirm: "Bu fuarı arşivlemek istediğinize emin misiniz?",
  restoreConfirm: "Bu fuarı arşivden çıkarmak istiyor musunuz?",
  restoreSuccess: "Fuar arşivden çıkarıldı.",
  searchPlaceholder: "Fuar ara…",
  noResults: "Fuar bulunamadı.",
  loadError: "Fuarlar yüklenemedi.",
  archiveError: "Arşivleme başarısız.",
  restoreError: "Arşivden çıkarma başarısız.",
  nameRequired: "Fuar adı zorunludur.",
  name: "Fuar Adı",
  organizer: "Organizatör",
  venue: "Mekan",
  start_date: "Başlangıç Tarihi",
  end_date: "Bitiş Tarihi",
  datePlaceholder: "YYYY-MM-DD",
  dateFormatHint:
    "Format: YYYY-MM-DD (ör. 2026-03-15) veya GG.AA.YYYY. Takvimden seçebilir veya klavye ile yazabilirsiniz.",
  dateInvalid: "Geçerli bir tarih girin (YYYY-MM-DD veya GG.AA.YYYY).",
  dateRangeInvalid: "Bitiş tarihi başlangıç tarihinden önce olamaz.",
  websitePlaceholder: "abc.com veya https://abc.com",
  websiteHint: "http/https yazmak zorunlu değildir (ör. abc.com, www.abc.com).",
  websiteInvalid: "Geçerli bir web sitesi girin (ör. abc.com veya https://abc.com).",
  fairSectionInfo: "Fuar Bilgileri",
  fairSectionScheduleLocation: "Tarih ve Lokasyon",
  fairSectionOrganization: "Organizasyon",
  fairSectionDetails: "Detaylar",
  dataIntegration: "Veri Entegrasyonu",
  adapter: "Adapter",
  sourceUrl: "Source URL",
  scraperConfig: "Scraper Config",
  lastImport: "Son Import",
  adapterNone: "Adapter seçilmedi",
  adapterSearchPlaceholder: "Adapter ara…",
  adapterNoResults: "Adapter bulunamadı.",
  adapterLoadError: "Adapter listesi yüklenemedi.",
  sourceUrlRequired: "Adapter seçildiğinde Source URL zorunludur.",
  sourceUrlInvalid: "Source URL geçerli bir http veya https adresi olmalıdır.",
  scraperConfigInvalid: "Scraper Config geçerli bir JSON nesnesi olmalıdır.",
  scraperConfigPlaceholder: '{"pagination": {"page_size": 50}}',
  runScraper: "Scraper Çalıştır ve Import Hazırla",
  runScraperSuccess: "Scraper çalıştırması başlatıldı.",
  runScraperComplete: "Import karar ekranına yönlendiriliyorsunuz…",
  runScraperNoRows: "Scraper tamamlandı ancak kayıt bulunamadı.",
  runScraperError: "Scraper çalıştırılamadı.",
  runScraperRunning: "Scraper çalışıyor…",

  enrichFairAction: "Zenginleştir",
  enrichFairModalTitle: "Fuar Katılımcılarını Zenginleştir",
  enrichFairModalLoadError: "Zenginleştirme ayarları yüklenemedi.",
  enrichFairBackToFair: "Fuara geri dön",
  enrichFairPermissionDenied: "Zenginleştirme çalıştırma yetkiniz yok (fair_crm.scraper.run).",

  bulkEmailCardTitle: "Toplu Mail Gönderimi",
  bulkEmailCardDescription:
    "Bu fuardaki katılımcı firmalara ve yetkili kişilere şablon kullanarak toplu e-posta gönderimi hazırlayın.",
  bulkEmailStartAction: "Mail Gönderimi Başlat",
  bulkEmailPermissionPreviewDeniedDebug: "Toplu mail önizleme yetkiniz yok (fair_crm.fair_emails.preview).",
  bulkEmailModalTitle: "Fuar Toplu Mail Gönder",
  bulkEmailOptionsSection: "Alıcı Kapsamı",
  bulkEmailIncludeCustomerEmails: "Bu fuardaki müşteri firma e-posta adreslerine gönder",
  bulkEmailIncludeContactEmails: "Bu fuardaki müşterilerin contact/yetkili kişi e-posta adreslerine de gönder",
  bulkEmailSkipNoEmail: "E-posta adresi olmayan kayıtları atla",
  bulkEmailExcludeInactive: "Pasif/arşivlenmiş müşteri ve contact kayıtlarını hariç tut",
  bulkEmailDedupeEmails: "Duplicate e-posta adreslerini tekilleştir",
  bulkEmailTemplateSection: "Mail Şablonu",
  bulkEmailTemplatePlaceholder: "Şablon seçin",
  bulkEmailSmtpPlaceholder: "Varsayılan SMTP hesabı",
  bulkEmailSubjectLabel: "Konu (subject)",
  bulkEmailPreviewAction: "Önizle",
  bulkEmailPreviewRunning: "Önizleme oluşturuluyor…",
  bulkEmailPreviewRequired: "Toplu mail göndermeden önce önizleme oluşturmalısınız.",
  bulkEmailPreviewStale: "Alıcı kapsamı değişti. Lütfen yeniden önizleyin.",
  bulkEmailRecipientsSection: "Alıcı Önizlemesi",
  bulkEmailContentSection: "Mail Önizlemesi",
  bulkEmailSendSubject: "Gönderilecek konu",
  bulkEmailSendSubjectHint:
    "Body şablondan render edilir; konu alanındaki değer test mail için override edilir.",
  bulkEmailSummaryCustomers: "Toplam müşteri",
  bulkEmailSummaryContacts: "Toplam contact",
  bulkEmailSummaryValidEmails: "Geçerli e-posta",
  bulkEmailSummaryDeduped: "Gönderilecek alıcı",
  bulkEmailSummarySkipped: "Atlanacak kayıt",
  bulkEmailColRecipient: "Alıcı",
  bulkEmailColCompany: "Firma",
  bulkEmailColEmail: "E-posta",
  bulkEmailColSource: "Kaynak",
  bulkEmailColStatus: "Durum",
  bulkEmailColSkipReason: "Atlanma sebebi",
  bulkEmailSourceCustomer: "Müşteri",
  bulkEmailSourceContact: "Contact",
  bulkEmailStatusWillSend: "Gönderilecek",
  bulkEmailStatusSkip: "Atlanacak",
  bulkEmailSkipReasonInactive: "Pasif kayıt",
  bulkEmailSkipReasonNoEmail: "E-posta yok",
  bulkEmailSkipReasonInvalidEmail: "Geçersiz e-posta",
  bulkEmailSkipReasonDuplicate: "Duplicate e-posta",
  bulkEmailSubmit: "Toplu Mail Gönder",
  bulkEmailSending: "Gönderim kuyruğa alınıyor…",
  bulkEmailSuccess: "Toplu mail gönderimi kuyruğa alındı.",
  bulkEmailError: "Toplu mail gönderilemedi.",
  bulkEmailLoadTemplatesError: "Mail şablonları yüklenemedi.",
  bulkEmailLoadSmtpError: "SMTP hesapları yüklenemedi.",
  bulkEmailSubjectRequired: "Konu (subject) zorunludur.",
  bulkEmailNoTemplates: "Aktif mail şablonu bulunamadı.",
  bulkEmailNoRecipients: "Gönderilecek alıcı bulunamadı.",
  bulkEmailPermissionPreviewDenied: "Alıcı önizlemesi için yetki gereklidir.",
  bulkEmailPermissionSendDenied: "Toplu mail göndermek için yetki gereklidir.",
  bulkEmailTemplateReadDenied: "Mail şablonlarını görüntüleme yetkiniz yok (fair_crm.mail_templates.read).",
  bulkEmailRenderPermissionDenied:
    "Mail önizlemesi için render yetkisi gereklidir (fair_crm.mail_templates.render).",
  bulkEmailLogsTitle: "Gönderim Logları",
  bulkEmailLogsEmpty: "Henüz toplu mail gönderimi yapılmadı.",
  bulkEmailLogsLoadError: "Gönderim logları yüklenemedi.",
  bulkEmailLogsDetailTitle: "Gönderim Detayı",
  bulkEmailLogsDetailAction: "Detay",
  bulkEmailLogsPolling: "Gönderim durumu güncelleniyor…",
  bulkEmailLogsColDate: "Tarih",
  bulkEmailLogsColTemplate: "Şablon",
  bulkEmailLogsColSmtp: "SMTP Hesabı",
  bulkEmailLogsColStatus: "Durum",
  bulkEmailLogsColTotal: "Toplam",
  bulkEmailLogsColSent: "Gönderildi",
  bulkEmailLogsColFailed: "Hatalı",
  bulkEmailLogsColQueued: "Kuyrukta",
  bulkEmailLogsColRecipient: "Alıcı",
  bulkEmailLogsColCompany: "Firma",
  bulkEmailLogsColSource: "Kaynak",
  bulkEmailLogsColEmail: "E-posta",
  bulkEmailLogsColError: "Hata",
  bulkEmailLogsColAttempts: "Deneme",
  bulkEmailLogsColSentAt: "Gönderim Zamanı",
  bulkEmailBatchStatusLabels: {
    queued: "Kuyrukta",
    processing: "İşleniyor",
    completed: "Tamamlandı",
    failed: "Başarısız",
    completed_with_errors: "Kısmen başarısız",
    partial_failed: "Kısmen başarısız",
  } as Record<string, string>,
  bulkEmailOutboxStatusLabels: {
    queued: "Kuyrukta",
    pending: "Kuyrukta",
    sending: "Gönderiliyor",
    sent: "Gönderildi",
    failed: "Hatalı",
    skipped: "Atlandı",
  } as Record<string, string>,
} as const;

export const fairStatusLabels: Record<string, string> = {
  planned: "Planlandı",
  active: "Aktif",
  completed: "Tamamlandı",
  cancelled: "İptal Edildi",
  archived: "Arşivlenmiş",
};
