export const importLabels = {
  imports: "İçe Aktarma",
  wizardTitle: "Akıllı İçe Aktarma",
  wizardSubtitle: "Adım adım güvenli veri aktarımı",
  stepSource: "Kaynak",
  stepUpload: "Yükle",
  stepFair: "Fuar Seçimi",
  stepMapping: "Kolon Eşleştirme",
  stepAnalyze: "Analiz",
  stepPreview: "Önizleme",
  stepDecisions: "Kararlar",
  stepApply: "Uygula",
  stepSummary: "Özet",
  sourceTitle: "Kaynak türünü seçin",
  sourceExcel: "Excel",
  sourceSoon: "Yakında",
  uploadTitle: "Dosyayı yükleyin",
  uploadHint: "Bu aşamada CRM kaydı oluşturulmaz. Yalnızca ham veri okunur.",
  selectFile: "Dosya Seç",
  upload: "Yükle",
  fairTitle: "Hedef fuarı seçin",
  fairSubtitle: "Tüm satırlar bu fuara katılımcı olarak içe aktarılacaktır.",
  fairSelect: "Fuar seçin",
  fairParticipants: "Mevcut katılımcı",
  mappingTitle: "Kolon eşleştirme",
  mappingSubtitle: "Her CRM alanını kaynak kolonuna bağlayın. Yalnızca firma adı zorunludur.",
  hasHeader: "İlk satır başlık mı?",
  headerYes: "Evet",
  headerNo: "Hayır",
  noMapping: "Eşleştirme yok",
  analyzeTitle: "Analiz",
  analyzeRun: "Analiz Et",
  analyzeRunning: "Analiz ediliyor…",
  previewTitle: "Önizleme",
  decisionsTitle: "Kararlar",
  applyTitle: "Uygula",
  applyConfirmTitle: "İçe Aktarmayı Uygula",
  applyConfirmMessage: "Seçili import kararları uygulanacak. Devam edilsin mi?",
  summaryTitle: "Özet",
  back: "Geri",
  next: "İleri",
  bulkCreateNew: "Tüm yenileri oluştur",
  bulkLinkExisting: "Tüm mevcut müşterileri fuara bağla",
  bulkUpdateDuplicates: "Tüm duplicate kayıtları güncelle",
  bulkSkipInvalid: "Tüm hatalıları atla",
  colRow: "Satır",
  colCompany: "Firma",
  colEmail: "E-posta",
  colPhone: "Telefon",
  colWeb: "Web",
  colHall: "Salon",
  colStand: "Stand",
  colStatus: "Durum",
  colMatch: "Eşleşen Müşteri",
  colParticipation: "Seçilen Fuarda Var mı?",
  colConfidence: "Güven",
  colDecision: "Karar",
  colErrors: "Hatalar",
  participationYes: "Mevcut katılım",
  participationNo: "Yeni katılım",
  resultCreated: "Oluşturulan müşteri",
  resultUpdated: "Güncellenen müşteri",
  resultParticipationCreated: "Oluşturulan katılım",
  resultParticipationUpdated: "Güncellenen katılım",
  resultContacts: "Oluşturulan contact",
  resultSkipped: "Atlanan",
  resultInvalid: "Hatalı",
  newImport: "Yeni içe aktarma",
  importFromFair: "Katılımcıları İçe Aktar",
  uploadError: "Dosya yüklenemedi.",
  loadError: "Veriler yüklenemedi.",
  applyError: "Uygulama başarısız.",
  decisionError: "Karar kaydedilemedi.",
  previewFilterAll: "Tümü",
  previewFilterNew: "Yeni",
  previewFilterUpdate: "Güncellenecek",
  previewFilterDuplicate: "Duplicate",
  previewFilterInvalid: "Hatalı",
  previewFilterSkip: "Atlanacak",
  previewSearch: "Firma ara…",
  previewSortConfidence: "Güven skoru",
  previewSortCompany: "Firma",
  previewSortStatus: "Durum",
  mergeDiffTitle: "Birleştirme Detayı",
  mappingCrmField: "CRM Alanı",
  mappingSourceColumn: "Kaynak Kolonu",
  mappingSourcePreview: "Kaynak Önizleme",
  mappingShowMoreSamples: "Diğer örnekleri göster",
  mappingShowLessSamples: "Daha az göster",
  mappingStatsTotal: "Toplam örnek",
  mappingStatsEmpty: "Boş",
  mappingStatsFilled: "Dolu",
  mappingStatsFirst: "İlk değer",
  mappingNoColumnSelected: "Kolon seçin",
} as const;

export const importBatchStatusLabels: Record<string, string> = {
  uploaded: "Yüklendi",
  mapped: "Eşleştirildi",
  analyzed: "Analiz edildi",
  previewed: "Önizlendi",
  applied: "Uygulandı",
  failed: "Başarısız",
  cancelled: "İptal Edildi",
};

export const importRowStatusLabels: Record<string, string> = {
  pending: "Bekliyor",
  valid: "Geçerli",
  invalid: "Hatalı",
  possible_duplicate: "Olası Tekrar",
  ready_to_create: "Yeni",
  ready_to_update: "Güncellenecek",
  applied: "Uygulandı",
  skipped: "Atlandı",
};

export const importDecisionLabels: Record<string, string> = {
  create_new: "Yeni müşteri oluştur",
  update_existing: "Mevcut müşteriyi güncelle/bağla",
  skip: "Atla",
};

export const WIZARD_STEPS = [
  { id: "source", label: importLabels.stepSource },
  { id: "fair", label: importLabels.stepFair },
  { id: "upload", label: importLabels.stepUpload },
  { id: "mapping", label: importLabels.stepMapping },
  { id: "analyze", label: importLabels.stepAnalyze },
  { id: "preview", label: importLabels.stepPreview },
  { id: "decisions", label: importLabels.stepDecisions },
  { id: "apply", label: importLabels.stepApply },
  { id: "summary", label: importLabels.stepSummary },
] as const;

export type WizardStepId = (typeof WIZARD_STEPS)[number]["id"];

export const mergeEntityLabels: Record<string, string> = {
  customer: "Müşteri",
  participation: "Fuar Katılımı",
  contact: "İletişim Kişisi",
};

export const mergeOutcomeLabels: Record<string, string> = {
  same: "Aynı",
  new: "Yeni",
  will_add: "Eklenecek",
  will_update: "Güncellenecek",
  will_keep: "Korunacak",
  conflict: "Çakışıyor",
  empty: "Boş",
  skipped: "Atlanacak",
};
