export const importLabels = {
  imports: "İçe Aktarma",
  uploadTitle: "Excel Dosyası Yükle",
  selectFile: "Dosya Seç",
  upload: "Yükle",
  uploadHint: "Sadece .xlsx dosyaları desteklenir",
  uploadError: "Dosya yüklenemedi.",
  loadError: "İçe aktarma verileri yüklenemedi.",
  apply: "İçe Aktarmayı Uygula",
  applyConfirmTitle: "İçe Aktarmayı Uygula",
  applyConfirmMessage: "Bu işlem seçili kararları uygulayacak. Devam edilsin mi?",
  applySuccess: "İçe aktarma tamamlandı.",
  applyError: "İçe aktarma uygulanamadı.",
  decisionError: "Karar kaydedilemedi.",
  summaryTotal: "Toplam Satır",
  summaryValid: "Geçerli",
  summaryInvalid: "Hatalı",
  summaryDuplicate: "Olası Tekrar",
  summaryCreate: "Oluşturulacak",
  summaryUpdate: "Güncellenecek",
  summarySkip: "Atlanacak",
  resultCreated: "Oluşturulan",
  resultUpdated: "Güncellenen",
  resultSkipped: "Atlanan",
  resultInvalid: "Hatalı",
  colRow: "Satır",
  colCompany: "Firma Adı",
  colEmail: "E-posta",
  colPhone: "Telefon",
  colContact: "Yetkili",
  colStatus: "Durum",
  colMatch: "Eşleşme",
  colConfidence: "Güven",
  colDecision: "Karar",
  colErrors: "Hatalar",
  decisionCreateNew: "Yeni müşteri oluştur",
  decisionUpdateExisting: "Mevcut müşteriyi güncelle",
  decisionSkip: "Atla",
  emptyTitle: "Henüz içe aktarma yapılmadı.",
  emptyDescription: "Excel dosyası yükleyerek başlayın.",
  previewTitle: "İçe Aktarma Önizleme",
} as const;

export const importBatchStatusLabels: Record<string, string> = {
  uploaded: "Yüklendi",
  previewed: "Önizlendi",
  applied: "Uygulandı",
  failed: "Başarısız",
  cancelled: "İptal Edildi",
};

export const importRowStatusLabels: Record<string, string> = {
  pending: "Bekliyor",
  valid: "Geçerli",
  invalid: "Hatalı",
  possible_duplicate: "Olası Tekrar",
  ready_to_create: "Oluşturulacak",
  ready_to_update: "Güncellenecek",
  applied: "Uygulandı",
  skipped: "Atlandı",
};

export const importDecisionLabels: Record<string, string> = {
  create_new: "Yeni müşteri oluştur",
  update_existing: "Mevcut müşteriyi güncelle",
  skip: "Atla",
};
