export const organizationLabels = {
  nav: "Organizasyonlar",
  title: "Organizasyonlar",
  newOrganization: "Yeni Organizasyon",
  editOrganization: "Organizasyonu Düzenle",
  organizationName: "Organizasyon Adı",
  nameRequired: "Organizasyon adı zorunludur.",
  save: "Kaydet",
  cancel: "İptal",
  edit: "Düzenle",
  delete: "Sil",
  actions: "İşlem",
  empty: "Henüz organizasyon yok",
  loadError: "Organizasyonlar yüklenemedi.",
  saveError: "Organizasyon kaydedilemedi.",
  deleteError: "Organizasyon silinemedi.",
  deleteTitle: "Organizasyonu Sil",
  deleteConfirm: "Bu organizasyon silinsin mi?",
};
