export const participationLabels = {
  tabCustomerFairs: "Katıldığı Fuarlar",
  tabFairParticipants: "Katılımcı Firmalar",
  addToFair: "Katılım Ekle",
  addCompany: "Katılım Ekle",
  fair: "Fuar",
  company: "Müşteri",
  hall: "Salon",
  stand: "Stand No",
  notes: "Not",
  actions: "İşlemler",
  newParticipation: "Katılım Ekle",
  editParticipation: "Katılım Düzenle",
  newParticipant: "Katılım Ekle",
  editParticipant: "Katılım Düzenle",
  save: "Kaydet",
  cancel: "İptal",
  delete: "Sil",
  edit: "Düzenle",
  deleteConfirm: "Bu katılım kaydı silinecek. Devam edilsin mi?",
  loadError: "Katılım kayıtları yüklenemedi.",
  deleteError: "Katılım kaydı silinemedi.",
  selectFair: "Fuar seçin",
  selectCompany: "Müşteri seçin",
  participationSectionInfo: "Katılım Bilgileri",
  participationSectionDetails: "Detaylar",
} as const;
