export const scraperLabels = {
  pageTitle: "Adapter Yönetimi",
  pageSubtitle: "Adapter kayıtlarını yönetin, test edin ve çalıştırın.",
  backToAdapters: "Adapter listesine dön",
  summaryTotal: "Toplam Adapter",
  summaryLastRun: "Son Çalışan",
  summaryLastError: "Son Hata",
  searchPlaceholder: "Adapter ara…",
  newAdapter: "Yeni Adapter",
  colAdapter: "Adapter",
  colVersion: "Version",
  colFeatures: "Features",
  colLastRun: "Last Run",
  colLastVerified: "Last Verified",
  colActions: "Actions",
  actionDetail: "Detay",
  actionOpenImport: "Import'a Git",
  actionEdit: "Düzenle",
  actionActivate: "Aktif Et",
  actionDeactivate: "Pasif Et",
  actionRun: "Çalıştır",
  editAdapter: "Adapter Düzenle",
  formAdapterKey: "Adapter Key",
  formAdapterKeyPlaceholder: "ornek_adapter",
  formAdapterName: "Adapter Adı",
  formAdapterNameRequired: "Adapter adı zorunludur.",
  formDescription: "Açıklama",
  formEngine: "Engine",
  formEngineDynamic: "Dynamic",
  formEngineDynamicHint:
    "Dynamic adapter henüz scrape edilemez. Regex/JSON/selector yapılandırması ileride eklenecek.",
  formEngineLoading: "Engine listesi yükleniyor…",
  formEngineLoadError: "Engine listesi yüklenemedi.",
  formRequestedFieldsRequired: "En az bir çıktı alanı seçilmelidir.",
  formManifestJson: "Manifest JSON",
  formManifestPlaceholder: '{"supports": {"list_scraping": true}}',
  formCreate: "Oluştur",
  formSave: "Kaydet",
  formCancel: "İptal",
  saveError: "Adapter kaydedilemedi.",
  manifestSaveError: "Manifest kaydedilemedi.",
  manifestNotes: "Notes",
  manifestInvalidJson: "Manifest geçerli bir JSON object olmalıdır.",
  inactiveBadge: "Pasif",
  runSoon: "Çalıştırma yakında kullanıma sunulacak.",
  emptyAdapters: "Henüz adapter bulunamadı.",
  loadError: "Adapter verileri yüklenemedi.",
  drawerTabManifest: "Manifest",
  drawerTabRunHistory: "Run History",
  drawerTabTestConsole: "Test",
  drawerTabLinkedFairs: "Bağlı Fuarlar",
  linkedFairColName: "Fuar Adı",
  linkedFairColLocation: "Lokasyon",
  linkedFairColStatus: "Durum",
  linkedFairColSourceUrl: "Source URL",
  linkedFairColLastImport: "Son Import",
  linkedFairOpenFair: "Fuarı Aç",
  linkedFairsEmpty: "Bu adapter henüz herhangi bir fuarda kullanılmıyor.",
  manifestOutputFields: "Çıktı Alanları",
  manifestOutputFieldsHint:
    "Scraper çıktısına dahil edilecek alanları seçin. Engine desteklemiyorsa alan seçilemez.",
  fieldSupported: "Destekleniyor",
  fieldNotSupported: "Desteklenmiyor",
  manifestOutput: "Çıktı",
  manifestBrowser: "Tarayıcı",
  manifestSites: "Desteklenen siteler",
  runColStarted: "Başlangıç",
  runColSource: "Kaynak",
  runColFairName: "Fuar",
  runColImportBatch: "Import Batch",
  runColStatus: "Durum",
  runColRows: "Kayıt",
  runColDuration: "Süre",
  runsEmpty: "Bu adapter için çalıştırma geçmişi yok.",
  testUrlLabel: "Taranacak URL",
  testUrlPlaceholder: "https://ornek.com/katilimci-listesi",
  testUrlRequired: "Lütfen taranacak URL girin.",
  testMaxPagesLabel: "Max Bakılacak Sayfa Sayısı",
  testMaxPagesPlaceholder: "Örn. 3",
  testMaxPagesHint:
    "Test için kaç liste sayfası taranacağını sınırlar. Boş bırakılırsa tüm sayfalar taranır.",
  testMaxPagesInvalid: "Max bakılacak sayfa sayısı en az 1 olmalıdır.",
  testRun: "Çalıştır",
  testRunning: "Çalışıyor…",
  testRunError: "Test çalıştırması başlatılamadı.",
  testStatusLabel: "Durum",
  testConsoleHint: "URL girip Çalıştır'a basın. Loglar burada görünecek.",
  testWaitingLogs: "Scraper başlatılıyor…",
  consolePolling: "Canlı loglar güncelleniyor…",
  testOutputHeading: "Test çıktıları",
  testOutputRecordCount: (count: number) => `${count.toLocaleString("tr-TR")} kayıt tamamlandı`,
  testOutputJsonDownload: "JSON indir",
  testOutputJsonOpen: "JSON aç",
  testOutputExcelDownload: "Excel indir",
  testOutputExcelOpen: "Excel aç",
  testOutputDownloadError: "Çıktı dosyası indirilemedi.",
  runStatusRunning: "Çalışıyor",
  runStatusCancelRequested: "Durduruluyor...",
  runStatusCancelling: "Durduruluyor...",
  runStatusCompleted: "Tamamlandı",
  runStatusFailed: "Başarısız",
  runStatusCancelled: "İptal edildi",
  enrichmentRunCancel: "Durdur",
  enrichmentRunCancelConfirmTitle: "Çalışmayı durdur",
  enrichmentRunCancelConfirmMessage:
    "Bu çalışmayı durdurmak istediğinize emin misiniz? İşlenen kayıtlar korunacak, işlenmeyen müşteriler untouched kalacaktır.",
  enrichmentRunCancelFailed: "Çalışma durdurulamadı.",
  runSourceFairAutomation: "Fuar otomasyonu",
  runSourceManualTest: "Manuel test",
  runHistoryTitle: "Scraper Run History",
  runHistorySubtitle: "Tüm adapter ve engine çalıştırmalarının merkezi geçmişi.",
  runColAdapterName: "Adapter Adı",
  runColAdapterKey: "Adapter Key",
  runColEngineKey: "Engine Key",
  runColEngineType: "Engine Type",
  runColInputUrl: "Taranan URL",
  runColFiles: "Dosyalar",
  runColDetail: "Detay",
  runFilterAdapter: "Adapter",
  runFilterStatus: "Durum",
  runFilterEngineType: "Engine Type",
  runFilterDateFrom: "Başlangıç tarihi",
  runFilterDateTo: "Bitiş tarihi",
  runFilterUrl: "URL ara",
  runFilterAll: "Tümü",
  runEngineTypeStatic: "Static",
  runEngineTypeDynamic: "Dynamic",
  runViewAllHistory: "Tüm Run History'yi Gör",
  runRecentSummary: "Son çalıştırmalar",
  runHistoryEmpty: "Henüz scraper çalıştırması yok.",
  testPageTitle: "Scraper Test",
  testPageSubtitle: "Adapter seçip URL girerek scraper test çalıştırması başlatın.",
  testAdapterLabel: "Adapter",
  testAdapterPlaceholder: "Adapter seçin…",
  testAdapterMeta: (engineKey: string, engineType: string) =>
    `Engine: ${engineKey} · ${engineType === "dynamic" ? "Dynamic" : "Static"}`,
  testSelectAdapterHint: "Test başlatmak için önce bir adapter seçin.",
  testOutputFormatsLabel: "Çıktı formatları",
  openInScraperTest: "Genel Test Ekranında Aç",
  openScraperTestForAdapter: "Bu adapter ile test çalıştır",
  enrichmentRunTab: "Çalıştır",
  enrichmentRunStart: "Zenginleştirmeyi Başlat",
  enrichmentRunRunning: "Çalışıyor…",
  enrichmentRunHint:
    "Website'i olan müşteriler seçilen alanlar için taranır. Bulunan yeni bilgiler Import Önizleme ekranında onayınıza sunulur.",
  enrichmentRunLimit: "Müşteri limiti",
  enrichmentRunLimitHint: "Boş bırakılırsa uygun tüm müşteriler işlenir.",
  enrichmentRunLimitInvalid: "Müşteri limiti 1 ile 500 arasında bir sayı olmalı veya boş bırakılmalıdır.",
  enrichmentRunFiltersHint:
    "Tüm filtreler isteğe bağlıdır. Amaç tüm datayı değil, filtreye uyan sınırlı müşteri grubunu zenginleştirmektir.",
  enrichmentRunFairFilter: "Fuar",
  enrichmentRunFairFilterHint: "Boş bırakılırsa tüm organizasyon müşterileri aday havuzuna girer.",
  enrichmentRunFairFilterClear: "Fuarı temizle",
  enrichmentRunFairFilterPlaceholder: "Fuar seçin (isteğe bağlı)",
  enrichmentRunCompanyName: "Firma adı",
  enrichmentRunCompanyNameHint: "Örn. SDK — boş bırakılabilir.",
  enrichmentRunCompanyNameMatch: "Firma adı eşleşmesi",
  enrichmentRunCompanyNameMatchContains: "İçinde geçen",
  enrichmentRunCompanyNameMatchStartsWith: "İle başlayan",
  enrichmentRunAddress: "Adres",
  enrichmentRunAddressHint: "Örn. İstanbul — adres veya şehir alanında geçenler.",
  enrichmentRunIncludeExistingEmail: "E-mail olanları da dahil et",
  enrichmentRunIncludeExistingEmailHint:
    "Açıkken CRM'de e-postası olan müşteriler de taranır. Mevcut veriler otomatik değişmez; bulunan bilgiler Import Önizleme'de onayınıza sunulur.",
  enrichmentRunStatus: "Durum",
  enrichmentRunFailed: "Zenginleştirme çalışması başarısız oldu.",
  enrichmentRunTimeout: "Çalıştırma zaman aşımına uğradı.",
  enrichmentRunMissingId: "Çalıştırma başlatıldı ancak sunucudan geçerli bir run kimliği alınamadı.",
  enrichmentRunRedirecting: "Çalıştırma başlatıldı, detay sayfasına yönlendiriliyorsunuz…",
  enrichmentRunRedirectUnavailable:
    "Çalıştırma başlatıldı ancak detay sayfasına otomatik yönlendirme yapılamadı.",
  enrichmentSummaryScanned: "Taranan müşteri",
  enrichmentSummaryEmailsFound: "E-posta bulunan",
  enrichmentSummaryNotFound: "Bulunamayan",
  enrichmentSummaryFailed: "Başarısız",
  enrichmentSummaryImportBatch: "Import batch",
  enrichmentSummaryImportBatchCreated: "Oluşturuldu",
  enrichmentSummaryImportBatchDryRun: "Önizleme modu — oluşturulmadı",
  enrichmentSummaryImportBatchNone: "Oluşturulmadı",
  enrichmentSummaryPendingDecision: "Onay bekleyen sonuç",
  enrichmentOpenImportBatch: "Import önizlemesine git",
  enrichmentRunAction: "Çalıştır",
  enrichmentStateResetTitle: "Durum / Reset",
  enrichmentStateResetIntro:
    "Organizasyondaki tüm müşterilerin enrichment durum kayıtlarını sıfırlar. Tek müşteri sıfırlama müşteri kartındaki İletişim Zenginleştirme sekmesinden yapılır.",
  enrichmentStateResetInfoCrm:
    "Bu işlem CRM'deki email/telefon verilerini silmez. Sadece enrichment state kayıtlarını temizler.",
  enrichmentStateResetAll: "Tüm enrichment state'i sıfırla",
  enrichmentStateResetConfirmAllTitle: "Tüm enrichment state'i sıfırla",
  enrichmentStateResetConfirmAllMessage:
    "Organizasyondaki tüm enrichment durum kayıtları silinecek. Müşteriler tekrar taranabilir hale gelir. Devam etmek istiyor musunuz?",
  enrichmentStateResetConfirmAction: "Sıfırla",
  enrichmentStateResetSuccess: "{count} enrichment durum kaydı silindi.",
  enrichmentStateResetFailed: "Enrichment durumu sıfırlanamadı.",
  enrichmentStateResetRunning: "Sıfırlanıyor…",
  enrichmentRunDetailTitle: "Zenginleştirme çalışması",
  enrichmentRunDetailSubtitle: "Canlı loglar ve özet",
  enrichmentRunDetailBackAdapter: "Adapter'a dön",
  enrichmentRunDetailBackHistory: "Çalışma geçmişi",
  enrichmentRunDetailBackEnrichment: "Zenginleştirmeye dön",
  enrichmentRunLogExport: "Logları Dışa Aktar",
  enrichmentRunLogExportTxt: "TXT",
  enrichmentRunLogExportJson: "JSON",
  enrichmentRunLogExporting: "Dışa aktarılıyor…",
  enrichmentRunLogExportFailed: "Loglar dışa aktarılamadı.",
  enrichmentLogCandidateSelected: "Aday seçildi",
  enrichmentLogWebsiteFetchStarted: "Web sitesi taranıyor",
  enrichmentLogWebsiteFetchSuccess: "Web sitesi yüklendi",
  enrichmentLogWebsiteFetchFailed: "Web sitesi yüklenemedi",
  enrichmentLogContactExtracted: "İletişim bilgisi çıkarıldı",
  enrichmentLogEmailFound: "E-posta bulundu",
  enrichmentLogNotFound: "E-posta bulunamadı",
  enrichmentLogHandoffRowCreated: "Import satırı oluşturuldu",
  enrichmentLogRunFinished: "Çalışma tamamlandı",
  runSourceEnrichment: "Müşteri zenginleştirme",
  deleteAdapter: "Adapter Sil",
  deleteAdapterTitle: "Adapter silinsin mi?",
  deleteAdapterError: "Adapter silinemedi.",
  deleteAdapterConfirmLabel: "Sil",
  buildDeleteAdapterMessage: (preview: {
    display_name: string;
    adapter_key: string;
    linked_fairs_count: number;
    active_runs_count: number;
  }) => {
    const lines = [
      `"${preview.display_name}" (${preview.adapter_key}) adapter'ı silinecek. Bu işlem geri alınamaz.`,
    ];
    if (preview.linked_fairs_count > 0) {
      lines.push(
        `Bu adapter ${preview.linked_fairs_count.toLocaleString("tr-TR")} fuara bağlı. Silerseniz bu fuarların adapter ilişkisi kaldırılacak.`,
      );
    }
    if (preview.active_runs_count > 0) {
      lines.push(
        `Bu adapter ile çalışan ${preview.active_runs_count.toLocaleString("tr-TR")} aktif iş var. Silerseniz bu işler iptal edilecek.`,
      );
    }
    lines.push("Devam etmek istiyor musunuz?");
    return lines.join("\n\n");
  },
};

/** @deprecated Use OUTPUT_FIELD_LABELS via getOutputFieldLabel() for output field keys. */
export const FEATURE_SHORT_LABELS: Record<string, string> = {
  customerName: "Firma",
  phone: "Tel",
  email: "E-posta",
  address: "Adres",
  website: "Web",
  hall: "Salon",
  stand: "Stand",
  instagram: "IG",
  facebook: "FB",
  linkedin: "LI",
  youtube: "YT",
  notes: "Not",
};

export const OUTPUT_FIELD_LABELS: Record<string, string> = {
  customerName: "Firma Adı",
  phone: "Telefon",
  email: "E-posta",
  address: "Adres",
  website: "Website",
  hall: "Salon",
  stand: "Stand",
  instagram: "Instagram",
  facebook: "Facebook",
  linkedin: "LinkedIn",
  youtube: "YouTube",
  notes: "Notlar",
};

/** @deprecated Use OUTPUT_FIELD_LABELS instead. */
export const REQUESTED_FIELD_LABELS = OUTPUT_FIELD_LABELS;
