export const scraperLabels = {
  pageTitle: "Adapter Yönetimi",
  pageSubtitle: "Adapter kayıtlarını yönetin, test edin ve çalıştırın.",
  backToAdapters: "Adapter listesine dön",
  summaryTotal: "Toplam Adapter",
  summaryStable: "Stable",
  summaryExperimental: "Experimental",
  summaryLastRun: "Son Çalışan",
  summaryLastError: "Son Hata",
  searchPlaceholder: "Adapter ara…",
  filterStatusAll: "Tüm durumlar",
  filterStatusStable: "Stable",
  filterStatusExperimental: "Experimental",
  filterStatusDeprecated: "Deprecated",
  newAdapter: "Yeni Adapter",
  colAdapter: "Adapter",
  colStatus: "Status",
  colVersion: "Version",
  colFeatures: "Features",
  colLastRun: "Last Run",
  colLastVerified: "Last Verified",
  colActions: "Actions",
  actionDetail: "Detay",
  actionEdit: "Düzenle",
  actionActivate: "Aktif Et",
  actionDeactivate: "Pasif Et",
  actionRun: "Çalıştır",
  editAdapter: "Adapter Düzenle",
  formAdapterKey: "Adapter Key",
  formAdapterKeyPlaceholder: "ornek_adapter",
  formAdapterName: "Adapter Adı",
  formDescription: "Açıklama",
  formManifestJson: "Manifest JSON",
  formManifestPlaceholder: '{"supports": {"list_scraping": true}}',
  formCreate: "Oluştur",
  formSave: "Kaydet",
  formCancel: "İptal",
  saveError: "Adapter kaydedilemedi.",
  manifestInvalidJson: "Manifest geçerli bir JSON object olmalıdır.",
  inactiveBadge: "Pasif",
  runSoon: "Çalıştırma yakında kullanıma sunulacak.",
  emptyAdapters: "Henüz adapter bulunamadı.",
  loadError: "Adapter verileri yüklenemedi.",
  drawerTabGeneral: "Genel",
  drawerTabManifest: "Manifest",
  drawerTabRunHistory: "Run History",
  drawerTabTestConsole: "Test Console",
  drawerTabLinkedFairs: "Bağlı Fuarlar",
  linkedFairColName: "Fuar Adı",
  linkedFairColLocation: "Lokasyon",
  linkedFairColStatus: "Durum",
  linkedFairColSourceUrl: "Source URL",
  linkedFairColLastImport: "Son Import",
  linkedFairOpenFair: "Fuarı Aç",
  linkedFairsEmpty: "Bu adapter henüz herhangi bir fuarda kullanılmıyor.",
  manifestSupports: "Desteklenen özellikler",
  manifestOutput: "Çıktı",
  manifestBrowser: "Tarayıcı",
  manifestSites: "Desteklenen siteler",
  runColStarted: "Başlangıç",
  runColStatus: "Durum",
  runColRows: "Kayıt",
  runColDuration: "Süre",
  runsEmpty: "Bu adapter için çalıştırma geçmişi yok.",
  consoleEmpty: "Görüntülenecek log yok. Run History sekmesinden bir çalıştırma seçin.",
  consoleSelectRun: "Çalıştırma seçin",
  consolePolling: "Canlı loglar güncelleniyor…",
  statusStable: "Stable",
  statusExperimental: "Experimental",
  statusDeprecated: "Deprecated",
  runStatusRunning: "Çalışıyor",
  runStatusCompleted: "Tamamlandı",
  runStatusFailed: "Başarısız",
};

export const FEATURE_SHORT_LABELS: Record<string, string> = {
  list_scraping: "List",
  detail_scraping: "Detail",
  pagination: "Page",
  website: "Web",
  email: "Mail",
  phone: "Phone",
};
