export const standProjectsLabels = {
  pageTitle: "Standlar",
  pageSubtitle: "Organizasyonunuza ait stand projelerini yönetin",
  navLabel: "Standlar",
  actionCreate: "Yeni Proje",
  actionEdit: "Düzenle",
  actionAssignCustomer: "Başka müşteriye ata",
  actionDelete: "Sil",
  colName: "Ad",
  colCustomer: "Müşteri",
  temporaryCustomer: "Geçici bağ",
  pickCustomerTitle: "Müşteri seç",
  pickCustomerConfirm: "Devam",
  pickCustomerDescription: "Yeni stand projesi bu müşteriye bağlanır.",
  assignCustomerTitle: "Başka müşteriye ata",
  assignCustomerDescription: (name: string) =>
    `"${name}" seçilen müşteriye bağlanır. Atama Kaydet ile yapılır.`,
  assignCustomerConfirm: "Kaydet",
  assignError: "Müşteri bağlanamadı.",
  missingCustomer: "Stand projesi açılmadan önce bir müşteri seçilmeli.",
  colUpdated: "Güncelleme",
  colCreated: "Oluşturma",
  colActions: "İşlemler",
  filterSearch: "Ara",
  filterSearchPlaceholder: "Proje adı…",
  emptyTitle: "Henüz proje yok",
  emptyDescription: "Yeni Proje ile ilk stand tasarımınızı oluşturun.",
  loadError: "Projeler yüklenemedi.",
  deleteError: "Proje silinemedi.",
  deleteConfirmTitle: "Projeyi sil",
  deleteConfirmDescription: (name: string) =>
    `"${name}" ve bu projeye ait tüm görseller silinecek. Bu işlem geri alınamaz.`,
  deleteConfirmAction: "Sil",
  backToList: "Standlar",
  editorNewTitle: "Yeni stand projesi",
  editorEditTitle: "Stand projesi",
  actionCalculate: "Maliyet Hesapla",
};

export const standProjectCostLabels = {
  pageTitle: "Maliyet Hesapla",
  exportExcel: "Excel İndir",
  pageSubtitle: "Güncel stand, güncel sahne elemanları ve güncel maliyet kalemlerinden hesaplanır. Bu hesap kaydedilmez.",
  denied: "Bu sayfayı görüntüleme yetkiniz yok.",
  loading: "Maliyet hesaplanıyor…",
  loadError: "Maliyet hesaplanamadı.",
  emptyTitle: "Hesaplanacak satır yok",
  emptyDescription: "Bu projenin güncel sahne elemanı listesi boş. Manuel kalem ekleyebilirsiniz.",
  missingPrice: "Fiyat yok",
  noTotal: "—",
  missingPriceNotice: (count: number) =>
    `${count} sahne elemanı satırında fiyat yok. Bu satırlar toplama dahil edilmez.`,
  filterSearch: "Ara",
  filterSearchPlaceholder: "Kalem ara…",
  searchEmptyTitle: "Eşleşen kalem yok",
  searchEmptyDescription: "Arama metnini değiştirin.",
  addManual: "Manuel Kalem Ekle",
  noManualItems: "Manuel maliyet kalemi yok",
  removeManual: "Kaldır",
  invalidQuantity: "Miktar pozitif olmalı.",
  colSource: "Kaynak",
  colName: "Maliyet Kalemi",
  colQuantity: "Miktar",
  colUnit: "Birim",
  colPurchaseUnit: "Alış Birim Fiyatı",
  colPurchaseTotal: "Alış Toplamı",
  colSaleUnit: "Satış Birim Fiyatı",
  colSaleTotal: "Satış Toplamı",
  sourceBom: "Sahne Elemanı",
  sourceManual: "Manuel",
  bandBomPurchase: "Sahne Elemanı Alış Tplm.",
  bandBomSale: "Sahne Elemanı Satış Tplm.",
  bandManualPurchase: "Manuel Alış Tplm.",
  bandManualSale: "Manuel Satış Tplm.",
  bandGrandPurchase: "Genel Alış Tplm.",
  bandGrandSale: "Genel Satış Tplm.",
};
