export const standProjectsLabels = {
  pageTitle: "Standlar",
  pageSubtitle: "Organizasyonunuza ait stand projelerini yönetin",
  navLabel: "Standlar",
  actionCreate: "Yeni Proje",
  actionEdit: "Düzenle",
  actionDelete: "Sil",
  colName: "Ad",
  colUpdated: "Güncelleme",
  colCreated: "Oluşturma",
  colActions: "İşlemler",
  filterSearch: "Ara",
  filterSearchPlaceholder: "Proje adı…",
  emptyTitle: "Henüz proje yok",
  emptyDescription: "Yeni Proje ile ilk stand tasarımınızı oluşturun.",
  loadError: "Projeler yüklenemedi.",
  deleteError: "Proje silinemedi.",
  deleteConfirmTitle: "Projeyi sil",
  deleteConfirmDescription: (name: string) =>
    `"${name}" ve bu projeye ait tüm görseller silinecek. Bu işlem geri alınamaz.`,
  deleteConfirmAction: "Sil",
  backToList: "Standlar",
  editorNewTitle: "Yeni stand projesi",
  editorEditTitle: "Stand projesi",
};
