export const standProjectsLabels = {
  pageTitle: "Standlar",
  pageSubtitle: "Organizasyonunuza ait stand projelerini yönetin",
  navLabel: "Standlar",
  actionCreate: "Yeni Proje",
  actionEdit: "Düzenle",
  actionAssignCustomer: "Başka müşteriye ata",
  actionDelete: "Sil",
  colName: "Ad",
  colCustomer: "Müşteri",
  temporaryCustomer: "Geçici bağ",
  pickCustomerTitle: "Müşteri seç",
  pickCustomerConfirm: "Devam",
  pickCustomerDescription: "Yeni stand projesi bu müşteriye bağlanır.",
  assignCustomerTitle: "Başka müşteriye ata",
  assignCustomerDescription: (name: string) =>
    `"${name}" seçilen müşteriye bağlanır. Atama Kaydet ile yapılır.`,
  assignCustomerConfirm: "Kaydet",
  assignError: "Müşteri bağlanamadı.",
  missingCustomer: "Stand projesi açılmadan önce bir müşteri seçilmeli.",
  colUpdated: "Güncelleme",
  colCreated: "Oluşturma",
  colActions: "İşlemler",
  filterSearch: "Ara",
  filterSearchPlaceholder: "Proje adı…",
  emptyTitle: "Henüz proje yok",
  emptyDescription: "Yeni Proje ile ilk stand tasarımınızı oluşturun.",
  loadError: "Projeler yüklenemedi.",
  deleteError: "Proje silinemedi.",
  deleteConfirmTitle: "Projeyi sil",
  deleteConfirmDescription: (name: string) =>
    `"${name}" ve bu projeye ait tüm görseller silinecek. Bu işlem geri alınamaz.`,
  deleteConfirmAction: "Sil",
  backToList: "Standlar",
  editorNewTitle: "Yeni stand projesi",
  editorEditTitle: "Stand projesi",
};
