import type { WorklistFilter, WorklistPrimaryStatus } from "../types/todoWorklist";

export const todoWorklistLabels = {
  worklistTitle: "Çalışma Listesi",
  progressTitle: "İlerleme",
  progressTotal: "Toplam",
  progressNotStarted: "Yapılmadı",
  progressInFollowUp: "Takipte",
  progressClosed: "Konu kapandı",
  filterYapilmadi: "Yapılmadı",
  filterTakipte: "Takipte",
  filterKonuKapandi: "Konu kapandı",
  filterHepsi: "Hepsi",
  colCustomer: "Müşteri",
  colCityCountry: "Şehir / Ülke",
  colPhone: "Telefon",
  colEmail: "E-posta",
  colLastOutcome: "Son sonuç",
  colLastNote: "Son not",
  colFollowUp: "Takip tarihi",
  colStatus: "Durum",
  colActions: "İşlemler",
  activityPanelTitle: "Müşteri işlemi",
  sectionCustomer: "Müşteri özeti",
  sectionNewActivity: "Yeni işlem",
  sectionFlags: "İşaretleme",
  outcomeLabel: "Sonuç",
  outcomePlaceholder: "Sonuç seçin",
  noteLabel: "Not",
  notePlaceholder: "Görüşme notunu yazın",
  followUpLabel: "Takip tarihi",
  actionRequiredLabel: "Aksiyon gerekiyor",
  actionRequiredHint: "Bu müşteri için ek takip veya işlem gerekir.",
  dataProblemLabel: "Veri problemi",
  dataProblemHint: "Müşteri kaydındaki eksik veya hatalı bilgiyi işaretler.",
  save: "Kaydet ve kapat",
  saveAndNext: "Kaydet ve sıradakine geç",
  saving: "Kaydediliyor…",
  openCustomerCard: "Müşteri Kartı",
  emptyWorklist: "Bu filtrede müşteri bulunamadı.",
  loadError: "Çalışma listesi yüklenemedi.",
  saveError: "Kayıt başarısız.",
  saveSuccess: "Kayıt tamamlandı.",
  missingSourceFair: "Bu görev için kaynak fuar tanımlı değil. Çalışma listesini kullanmak için görevi düzenleyip bir fuar seçin.",
  missingSourceFairAction: "Görevler listesinden Düzenle ile kaynak fuar atayabilirsiniz.",
  recentActivities: "Son aktiviteler",
  recentActivitiesOverflow: "+{count} aktivite daha",
  backToList: "Görev listesine dön",
  addedAfterCompletionBadge: "Sonradan eklendi",
  mailSendAction: "Mail Gönder",
  manualMailModalTitle: "Manuel Mail Gönder",
  manualMailRecipientsSection: "Alıcılar",
  manualMailContentSection: "Mail içeriği",
  manualMailRecipientPicker: "Alıcı seç",
  manualMailRecipientPlaceholder: "Müşteri veya contact e-postası seçin",
  manualMailManualAdd: "Elle e-posta ekle",
  manualMailManualPlaceholder: "ornek@firma.com",
  manualMailAddRecipient: "Ekle",
  manualMailRemoveRecipient: "Alıcıyı kaldır",
  manualMailRecipientsList: "Alıcı listesi",
  manualMailNoRecipients: "Henüz alıcı eklenmedi.",
  manualMailCustomerEmail: "Müşteri",
  manualMailContactEmail: "Contact",
  manualMailSmtpAccount: "SMTP hesabı",
  manualMailSmtpPlaceholder: "SMTP hesabı seçin",
  manualMailTemplate: "Mail şablonu",
  manualMailTemplatePlaceholder: "Şablon seçin (opsiyonel)",
  manualMailSubject: "Konu",
  manualMailBody: "Gövde",
  manualMailSend: "Gönder",
  manualMailSending: "Gönderiliyor…",
  manualMailQueuedSuccess: "Mail gönderimleri kuyruğa alındı.",
  manualMailSendError: "Mail kuyruğa alınamadı.",
  manualMailLoadError: "Mail formu yüklenemedi.",
  manualMailInvalidEmail: "Geçerli bir e-posta adresi girin.",
  manualMailDuplicateEmail: "Bu e-posta adresi zaten eklendi.",
  manualMailPreviewAction: "Önizle",
  manualMailPreviewRunning: "Önizleniyor…",
  manualMailPreviewRequired: "Göndermeden önce maili önizleyin.",
  manualMailPreviewStale: "İçerik değişti. Göndermeden önce tekrar önizleyin.",
  manualMailPreviewSection: "Mail önizleme",
  manualMailPreviewTemplate: "Şablon",
  manualMailPreviewRecipients: "Alıcılar",
  manualMailPreviewSmtp: "Gönderen SMTP hesabı",
  manualMailPreviewSubject: "Konu",
  manualMailPreviewBody: "Gövde",
  manualMailPreviewBack: "Düzenlemeye Dön",
  manualMailUnresolvedVariables: "Şablonda doldurulamayan değişkenler bulunuyor.",
  manualMailPreviewFormIncomplete: "Önizleme için alıcı, SMTP, konu ve gövde zorunludur.",
} as const;

export const worklistFilterOptions: { value: WorklistFilter; label: string }[] = [
  { value: "yapilmadi", label: todoWorklistLabels.filterYapilmadi },
  { value: "takipte", label: todoWorklistLabels.filterTakipte },
  { value: "konu_kapandi", label: todoWorklistLabels.filterKonuKapandi },
  { value: "hepsi", label: todoWorklistLabels.filterHepsi },
];

export const worklistStatusLabels: Record<WorklistPrimaryStatus, string> = {
  not_started: todoWorklistLabels.progressNotStarted,
  in_follow_up: todoWorklistLabels.progressInFollowUp,
  closed: todoWorklistLabels.progressClosed,
};

export function worklistStatusBadgeVariant(
  status: WorklistPrimaryStatus,
): "default" | "warning" | "success" {
  if (status === "in_follow_up") return "warning";
  if (status === "closed") return "success";
  return "default";
}
