export const uiLabels = {
  confirm: "Onayla",
  delete: "Sil",
  createNew: "Yeni Oluştur",
  searchCustomer: "Müşteri ara...",
  searchContact: "İletişim kişisi ara...",
  searchActivity: "Aktivite ara...",
  searchFair: "Fuar ara...",
  navCustomers: "Müşteriler",
  navDashboard: "Dashboard",
  navFairs: "Fuarlar",
  navTodos: "Görevler",
  navFollowUps: "Takipler",
  navImports: "Veri Entegrasyonu",
  navAdmin: "Admin",
  sidebarCollapse: "Menüyü daralt",
  sidebarExpand: "Menüyü genişlet",
  diSubnavCollapse: "Alt menüyü daralt",
  diSubnavExpand: "Alt menüyü genişlet",
  breadcrumbHome: "Ana Sayfa",
  tabOverview: "Genel Bilgiler",
  tabContacts: "İletişim Kişileri",
  tabActivities: "Aktiviteler",
  tabFairParticipations: "Katıldığı Fuarlar",
  emptyContactsTitle: "Henüz iletişim kişisi eklenmedi.",
  emptyContactsDescription: "Bu müşteri için iletişim kişisi ekleyerek başlayın.",
  emptyActivitiesTitle: "Henüz aktivite bulunmuyor.",
  emptyActivitiesDescription: "Görüşme, not veya takip kaydı ekleyerek zaman çizelgesini oluşturun.",
  emptyCustomersTitle: "Müşteri bulunamadı.",
  emptyCustomersDescription: "Arama kriterlerinizi değiştirin veya yeni müşteri ekleyin.",
  emptySearchTitle: "Sonuç bulunamadı.",
  emptySearchDescription: "Arama veya filtre kriterlerinizi değiştirip tekrar deneyin.",
  deleteContactTitle: "İletişim Kişisini Sil",
  deleteActivityTitle: "Aktiviteyi Sil",
  detailEdit: "Düzenle",
  detailAddContact: "İletişim Kişisi Ekle",
  detailNewActivity: "Yeni Aktivite",
  detailFairActivitySoon: "Fuar aktivitesi yakında",
  backToFairs: "Fuarlara Dön",
  modalUnsavedTitle: "Kaydedilmemiş değişiklikler",
  modalUnsavedMessage:
    "Kaydedilmemiş değişiklikler var. Çıkmak istediğinize emin misiniz?",
  modalReturnToForm: "Forma Dön",
  modalDiscardExit: "Çık",
  showPassword: "Şifreyi göster",
  hidePassword: "Şifreyi gizle",
  technicalDetails: "Teknik detaylar",
  expandRow: "Satırı genişlet",
  collapseRow: "Satırı daralt",
  expandDetails: "Detayları göster",
  collapseDetails: "Detayları gizle",
} as const;
