"""PostgreSQL custom-archive evidence on a disposable database.

The test never connects to fair_crm, kyrox_core, or fair_stand.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from app.shared.database_backup.table_selection import parse_restore_toc_tables, restore_list_for_tables

CONTAINER = "kyrox-postgres-dev"
SOURCE_DB = "kyrox_tblsel_probe"
RESTORE_DB = "kyrox_tblsel_restore"


def _docker_ready() -> bool:
    if shutil.which("docker") is None:
        return False
    proc = subprocess.run(
        ["docker", "inspect", "-f", "{{.State.Running}}", CONTAINER],
        capture_output=True,
        text=True,
        check=False,
    )
    return proc.returncode == 0 and proc.stdout.strip() == "true"


pytestmark = pytest.mark.skipif(not _docker_ready(), reason="kyrox-postgres-dev is not running")


def _psql(database: str, sql: str) -> str:
    proc = subprocess.run(
        [
            "docker",
            "exec",
            CONTAINER,
            "psql",
            "-U",
            "postgres",
            "-d",
            database,
            "-v",
            "ON_ERROR_STOP=1",
            "-At",
            "-c",
            sql,
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise AssertionError(proc.stderr.strip() or proc.stdout.strip())
    return proc.stdout


def _pg(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["docker", "exec", CONTAINER, *args],
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.fixture
def disposable_databases():
    _psql("postgres", f"DROP DATABASE IF EXISTS {SOURCE_DB} WITH (FORCE)")
    _psql("postgres", f"DROP DATABASE IF EXISTS {RESTORE_DB} WITH (FORCE)")
    _psql("postgres", f"CREATE DATABASE {SOURCE_DB}")
    _psql("postgres", f"CREATE DATABASE {RESTORE_DB}")
    _psql(
        SOURCE_DB,
        """
        CREATE TABLE parent_probe (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text UNIQUE
        );
        CREATE TABLE child_probe (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id integer NOT NULL REFERENCES parent_probe(id),
            note text
        );
        CREATE INDEX ix_child_probe_note ON child_probe (note);
        INSERT INTO parent_probe (name) VALUES ('alpha');
        INSERT INTO child_probe (parent_id, note) VALUES (1, 'beta');
        """,
    )
    try:
        yield
    finally:
        _psql("postgres", f"DROP DATABASE IF EXISTS {SOURCE_DB} WITH (FORCE)")
        _psql("postgres", f"DROP DATABASE IF EXISTS {RESTORE_DB} WITH (FORCE)")
        _pg(
            [
                "rm",
                "-f",
                "/tmp/kyrox_tblsel_full.dump",
                "/tmp/kyrox_tblsel_child.dump",
                "/tmp/kyrox_tblsel_both.dump",
                "/tmp/kyrox_tblsel_child.list",
                "/tmp/kyrox_tblsel_both.list",
            ]
        )


def test_custom_archive_table_selection_uses_native_objects(disposable_databases, tmp_path):
    full = _pg(
        [
            "pg_dump",
            "-Fc",
            "--no-owner",
            "--no-acl",
            "-U",
            "postgres",
            "-d",
            SOURCE_DB,
            "-f",
            "/tmp/kyrox_tblsel_full.dump",
        ]
    )
    assert full.returncode == 0, full.stderr
    child = _pg(
        [
            "pg_dump",
            "-Fc",
            "--no-owner",
            "--no-acl",
            "-U",
            "postgres",
            "-d",
            SOURCE_DB,
            "-t",
            "public.child_probe",
            "-f",
            "/tmp/kyrox_tblsel_child.dump",
        ]
    )
    assert child.returncode == 0, child.stderr
    both = _pg(
        [
            "pg_dump",
            "-Fc",
            "--no-owner",
            "--no-acl",
            "-U",
            "postgres",
            "-d",
            SOURCE_DB,
            "-t",
            "public.parent_probe",
            "-t",
            "public.child_probe",
            "-f",
            "/tmp/kyrox_tblsel_both.dump",
        ]
    )
    assert both.returncode == 0, both.stderr

    full_toc = _pg(["pg_restore", "-l", "/tmp/kyrox_tblsel_full.dump"])
    child_toc = _pg(["pg_restore", "-l", "/tmp/kyrox_tblsel_child.dump"])
    both_toc = _pg(["pg_restore", "-l", "/tmp/kyrox_tblsel_both.dump"])
    assert full_toc.returncode == 0
    assert child_toc.returncode == 0
    assert both_toc.returncode == 0
    assert sorted(parse_restore_toc_tables(full_toc.stdout)) == ["public.child_probe", "public.parent_probe"]
    assert parse_restore_toc_tables(child_toc.stdout) == ["public.child_probe"]
    assert sorted(parse_restore_toc_tables(both_toc.stdout)) == ["public.child_probe", "public.parent_probe"]
    for marker in ("SEQUENCE", "SEQUENCE SET", "TABLE DATA", "CONSTRAINT", "INDEX", "FK CONSTRAINT"):
        assert marker in child_toc.stdout
    assert "public parent_probe" not in child_toc.stdout

    verbose = _pg(["pg_restore", "-l", "-v", "/tmp/kyrox_tblsel_full.dump"])
    assert verbose.returncode == 0, verbose.stderr
    child_list = tmp_path / "child.list"
    both_list = tmp_path / "both.list"
    child_list.write_text(restore_list_for_tables(verbose.stdout, ["public.child_probe"]), encoding="utf-8")
    both_list.write_text(
        restore_list_for_tables(verbose.stdout, ["public.parent_probe", "public.child_probe"]),
        encoding="utf-8",
    )
    child_active = "\n".join(line for line in child_list.read_text(encoding="utf-8").splitlines() if line[:1].isdigit())
    assert "parent_probe" not in child_active
    assert "FK CONSTRAINT" in child_active
    subprocess.run(["docker", "cp", str(child_list), f"{CONTAINER}:/tmp/kyrox_tblsel_child.list"], check=True)
    subprocess.run(["docker", "cp", str(both_list), f"{CONTAINER}:/tmp/kyrox_tblsel_both.list"], check=True)

    child_only = _pg(
        [
            "pg_restore",
            "--clean",
            "--if-exists",
            "--single-transaction",
            "--no-owner",
            "--no-acl",
            "--exit-on-error",
            "-U",
            "postgres",
            "-d",
            RESTORE_DB,
            "-L",
            "/tmp/kyrox_tblsel_child.list",
            "/tmp/kyrox_tblsel_full.dump",
        ]
    )
    assert child_only.returncode != 0
    assert "parent_probe" in (child_only.stderr or "")
    assert _psql(RESTORE_DB, "SELECT to_regclass('public.child_probe') IS NULL") == "t\n"

    restored = _pg(
        [
            "pg_restore",
            "--clean",
            "--if-exists",
            "--single-transaction",
            "--no-owner",
            "--no-acl",
            "--exit-on-error",
            "-U",
            "postgres",
            "-d",
            RESTORE_DB,
            "-L",
            "/tmp/kyrox_tblsel_both.list",
            "/tmp/kyrox_tblsel_full.dump",
        ]
    )
    assert restored.returncode == 0, restored.stderr
    assert _psql(RESTORE_DB, "SELECT count(*) FROM parent_probe") == "1\n"
    assert _psql(RESTORE_DB, "SELECT count(*) FROM child_probe") == "1\n"
    assert _psql(RESTORE_DB, "SELECT count(*) FROM pg_constraint WHERE conname = 'child_probe_pkey'") == "1\n"
    assert _psql(RESTORE_DB, "SELECT count(*) FROM pg_constraint WHERE conname = 'parent_probe_name_key'") == "1\n"
    assert _psql(RESTORE_DB, "SELECT count(*) FROM pg_constraint WHERE conname = 'child_probe_parent_id_fkey'") == "1\n"
    assert _psql(RESTORE_DB, "SELECT count(*) FROM pg_indexes WHERE indexname = 'ix_child_probe_note'") == "1\n"
    assert _psql(RESTORE_DB, "SELECT pg_get_serial_sequence('public.child_probe','id')") == "public.child_probe_id_seq\n"

    _psql("postgres", f"DROP DATABASE IF EXISTS {RESTORE_DB} WITH (FORCE)")
    _psql("postgres", f"CREATE DATABASE {RESTORE_DB}")
    full_restore = _pg(
        [
            "pg_restore",
            "--clean",
            "--if-exists",
            "--single-transaction",
            "--no-owner",
            "--no-acl",
            "--exit-on-error",
            "-U",
            "postgres",
            "-d",
            RESTORE_DB,
            "/tmp/kyrox_tblsel_full.dump",
        ]
    )
    assert full_restore.returncode == 0, full_restore.stderr
    assert _psql(RESTORE_DB, "SELECT name FROM parent_probe") == "alpha\n"
